
<div class="row">

    <div class="tab-content">

        <table class="table">
            <thead>
                <tr>
                    <th>id</th>
                     <th>itemid</th>
                      <th>almacen</th>
                       <th>localidad</th>
                        <th>usuario</th>
                        <th>fecha</th>
                        <th>cambio</th>
                </tr>
            </thead>
            <tbody>
                <?php echo $this->bodytable ?>
            </tbody>
        </table>
    </div>
</div>

<script>
    $(".table").DataTable();
</script>