<script>
    var payModeList=<?php echo json_encode($this->payMode);?>;
</script>
<div class="col-lg-12">
    <div class="panel panel-primary">
        <div class="panel-heading"> Nuevo diario 
            <div class="pull-right">
                <div class="btn-group">
                    <button  style="margin-top: -7px;" onclick="crearDiario()" type="button" class="btn btn-success"><i class="fa fa-save" ></i> Guardar</button>
                </div>                
            </div>
        </div>
        <div class="panel-body">
            <form id="diarioPagoForm">
                <div class="row">
                    <div class="col-md-4">
                        <label>Nombre:</label>
                        <select  class="form-control" name="contrapartida" id="contraPartida" class="browser-default"><option></option></select>
                    </div>                        
                    <div class="col-md-8">
                        <label>Descripción:</label>
                        <input class="form-control" name="descripcion" value="<?= $this->fechaInput ?> Cobros" >
                    </div>                
                </div>
                <hr>
                <div class="row">
                    <div class="col-md-2">
                        <label>Fecha</label>
                        <input class="form-control" type="date" name="fecha" value="<?= $this->fechaInput ?>" readonly="">
                    </div>                
                    <div class="col-md-2">
                        <label>Factura</label>
                        <input class="form-control" id="diarioFacturaFolio" type="text" name="factura">
                    </div>
                    <div class="col-md-2">
                        <label>Crédito</label>
                        <input class="form-control" id="diarioMontoFactura" type="number" name="diarioMontoFactura" value="">
                    </div>
                    <div class="col-md-3">
                        <label>Cuenta de contrapartida</label>
                        <select class="form-control" id="diarioCuentaContra" name="diarioCuentaContra" ></select>
                    </div>
                    <div class="col-md-3">
                        <label>Tipo de Pago</label>
                        <select id="diarioFPago" name="diarioFPago" class="form-control" onchange="diarioFormaPago(this.value)"></select>
                    </div>
                </div>
            </form>          
        </div>
    </div>
</div>
<div class="col-lg-12">
    <div class="panel panel-primary">
        <div class="panel-heading">Lista Diarios de pago 
            <div class="pull-right">
                <div class="btn-group">                
                    <input type="date" name="f1" id="f1" value="<?= $this->fechaInput ?>" style="color: black;" onchange="filter();"> al
                    <input type="date" name="f2" id="f2" value="<?= $this->fechaInput ?>" style="color: black;" onchange="filter();"> 
                </div>
            </div>
        </div>
        <div class="panel-body">
            <div class="col-lg-12">
                <table id="tabla" class="table table-striped table-responsive">
                    <thead>
                        <tr>
                            <th><label>Diario</label></th>
                            <th><label>Descripción</label></th>
                            <th><label>Nombre</label></th>
                            <th><label>Fecha</label></th>                            
                        </tr>
                    </thead>
                    <tbody></tbody>
                </table>               
            </div>
        </div>
    </div>
</div>
<div id="detalleDiario" class="modal fade" role="dialog">
    <div class="modal-dialog" style="width: 75%">
        <div class="modal-content">
            <div class="modal-header bg-warning">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Detalle de diario <span id="diarioFolio"></span></h4>
            </div>
            <div class="modal-body">
                <table id="diarioDetalle"></table>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
            </div>
        </div>
    </div>
</div>
<div id="editarDiario" class="modal fade" role="dialog">
    <div class="modal-dialog" style="width: 75%">
        <div class="modal-content">
            <div class="modal-header bg-info">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Editar diario <span id="diarioFolioEditar"></span></h4>
            </div>
            <div class="modal-body">
                <form id="diarioForm">
                    <input type="hidden" name="diario" value="" id="diarioHidden">
                    <table id="diarioDetalleEditar" class="table table-striped">
                        <thead><tr><th>Cuenta</th><th>Factura</th><th>Descripción</th><th>Crédito</th><th>PayMode</th><th>Cuenta De Contrapartida</th></tr></thead>
                        <tbody></tbody>
                    </table>
                </form>                
            </div>
            <div class="modal-footer">
                <button onclick="guardarDiario()" type="button" class="btn btn-success"><i class="fa fa-save" ></i> Guardar</button>
                <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
            </div>
        </div>
    </div>
</div>
<script src="<?= JAVASCRIPT_PATH ?>/views/diarios.js?v=<?php echo date("d"); ?>" type="text/javascript"></script>
<script>
    filter();
    nuevoDiarioModalOpen();   
    autocompleteSetLabel(mapArray(<?= $this->facturas ?>),'#diarioFacturaFolio');
</script>