<?php /* echo $this->doctype(); */ $meses = array('January'    => 'Enero','February'  => 'Febrero','March'     => 'Marzo','April'     => 'Abril','May'       => 'Mayo','June'      => 'Junio','July'      => 'Julio','August'    => 'Agosto','September' => 'Septiembre','October'   => 'Octubre','November'  => 'Noviembre','December'  => 'Diciembre',); date_default_timezone_set('America/Chihuahua'); $fecha = new DateTime(); $mes   = $fecha->format('F'); $fecha = $meses[$mes].'/'.$fecha->format('Y'); $fecha = new DateTime(); $mes   = $fecha->format('F'); $fecha = $meses[$mes].'/'.$fecha->format('Y');
if ( isset($_SESSION['userInax']) ){$user = $_SESSION['userInax'];$visible = 'none'; if ($user === 'sistemas07' || $user === 'ventascat21'|| $user === 'sistemas10' || $user === 'sistemas' || $user == 'supervisor.cat'){ $visible = 'block';} } ?>
<!DOCTYPE html>
<html>
<head>
	<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
	<meta charset="UTF-8" />
	<title><?= VERSION ?> - <?php echo $_SESSION['company_name']; ?></title>
        <link href="../application/assets/img/logo_inax.png" rel="icon" />
        <link href="../application/assets/css/font-google.css" media="screen" rel="stylesheet" type="text/css" />
        <link href="../application/assets/css/buttons/css/buttons.dataTables.css" media="screen" rel="stylesheet" type="text/css" />
        <link href="../application/assets/css/jquery.dataTables.min.css" media="screen" rel="stylesheet" type="text/css" />
        <link href="../application/assets/css/jquery-ui.css" media="screen" rel="stylesheet" type="text/css" />
        <link href="../application/assets/css/icon.css" media="screen" rel="stylesheet" type="text/css" />
        <link href="../application/assets/fa/css/font-awesome.min.css" media="screen" rel="stylesheet" type="text/css" />
        <link href="../application/assets/css/select2.css" media="screen" rel="stylesheet" type="text/css" /><script type="text/javascript" src="../application/assets/js/tickets.js?v=10Thu"></script>
        <link rel="stylesheet" href="../application/assets/css/loading.css">
        <link rel="stylesheet" href="../application/assets/css/menu-superior.css">
        <link rel="stylesheet" href="../application/assets/bootstrap/css/bootstrap.css">
        <link rel="stylesheet" href="../application/assets/bootstrap/css/bootstrap-theme.css">
        <link rel="stylesheet" href="../application/assets/bootstrap/css/sb-admin-2.css">
        <link rel="stylesheet" href="../application/assets/bootstrap/css/metisMenu.min.css">        
        <link rel="stylesheet" href="../application/assets/bootstrap/css/bootstrap-multiselect.css" type="text/css">
        <link rel="stylesheet" href="../application/assets/css/views/bootstrap.css" type="text/css">
        <link rel="stylesheet" href="../application/assets/css/sweetalert2.css">
        
        <!-- Global site tag (gtag.js) - Google Analytics -->
        <script async src="https://www.googletagmanager.com/gtag/js?id=UA-112524741-1"></script>
        <script>
          flagFactura=<?php (!empty($_SESSION['factura'])) ? print_r(json_encode($_SESSION['factura'])) : print_r(json_encode(array())); ?>;
          window.dataLayer = window.dataLayer || [];
          function gtag(){dataLayer.push(arguments);}
          gtag('js', new Date());
          gtag('config', 'UA-112524741-1');
        </script>   
        <script type="text/javascript" src="../application/assets/js/jQuery-2.1.4.js"></script>
        <script type="text/javascript" src="../application/assets/js/jquery.min.js"></script>
</head>
<body onLoad="">
    <!-- <nav> -->
    <!-- Menú Superior -->
    <?php if(CONFIG=='AOS06'){ ?>
        <div class="bg-danger white-text" id="mensajesDev" style="margin: 0; padding: 5px;"><?= MESSAGE ?></div>
    <?php } ?>
<!-- Inicia: Modal (About) -->
<div class="modal fade" role="dialog" id="modal-about">
    <div class="modal-dialog ">
        <div class="modal-content">
            <div class="modal-header bg-primary">
                <label class="text-center"><?= VERSION?>.</label>
            </div>
            <div class="modal-body">
                <p class="text-white">Se autoriza el uso de este software a:</p>
                <p ><h5><?= $_SESSION['company_name']; ?></h5></p>
                <p >En esta version se incluye:</p>
                <p >* Aplicacion de algunos atajos con el teclado los podras ver colocando el mouse en el menú</p>
                <p >* Proximanete algunas graficas de ventas con estadisticas de uso de InAX</p>
                <p >* Incorporacion de menú para acceso mas rapido a las opciones del sistema</p>
                <p class="text-align: right;"><?= VERSION ?></p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-dismiss="modal">Cerrar</button>
            </div>
        </div>                    
    </div>
</div>
<div class="modal fade" role="dialog" id="modal-ticket">
    <div class="modal-dialog modal-lg">
    <div class="modal-content">                
        <div class="modal-header bg-red text-center"><label style="color:white;">Nuevo Ticket</label></div>
        <div class="modal-body">
        <form id="formSendTicket" action="../public/inicio/ticket" method="POST">
            <div class="row">							
                <div class="col-lg-6">
                    <b>Categoria :</b> inAX <br>
                    <b>Subcatgoria :</b>Incidencia INAX
                    <label for="">Elemento</label>
                    <select name="elemento" class="form-control">
                        <option value="Otro" selected>Otro</option>
                        <option value="Confirmacion de Cotizacion">Confirmacion de cotizacion</option>
                        <option value="Precios">Precios</option>
                    </select>
                    <label for="">Mandar captura de pantalla</label>
                    <select name="select_send_atachment" class="form-control">
                        <option value="1"  selected>Si</option>
                        <option value="0">No</option>
                    </select>
                </div>
                <div class="col-lg-6">                                
                    <div id="imgTiket" style="height: 168px;"></div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-12">
                    <label>Detalle el problema</label>
                    <textarea name="textTicket"   style="float: right;height: 150px;" class="form-control"></textarea>
                    <input name="base64" type="hidden" id="base64">
                </div>
            </div>
        </form>
        </div>
        <div class="modal-footer">
            <button class="btn btn-primary" onclick="mandarTicket();">Enviar Ticket</button>
            <button type="button" class="btn btn-danger" data-dismiss="modal">Cerrar</button>                        
        </div>
    </div>
    </div>
</div>
<div id="wrapper">
    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-static-top" role="navigation" style="margin-bottom: 0">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="./?<?php echo $_SESSION['userInax']?>">
                 <?php 
                 if(COMPANY=="ATP"){ ?><img src="<?= IMAGES_PATH ?>/avance-logo.png"  class="responsive-img"><?php }
                 else{ ?> <img src="<?= IMAGES_PATH ?>/lideart270x78.png"  class="responsive-img"> <?php } ?></a>
        </div>
        <ul class="nav navbar-top-links navbar-right">
            <li class="dropdown"><div style="color: #ffffff;">Tipo de cambio: <?= $_SESSION['tipoC'] ?> <span id="tipoCambio"></span></div></li>
            <li class="dropdown">                    
                <label style="color: #ffffff;" class="dropdown-toggle" data-toggle="dropdown">
                    <i class="fa fa-user fa-fw"></i> <?=  $_SESSION['userInax'] ?> <i class="fa fa-caret-down"></i>
                </label>
                <ul class="dropdown-menu dropdown-user">
                    <li><a data-toggle="modal" data-target="#modal-about"><i class="fa fa-user fa-fw"></i> Versión</a>
                    </li>
                    <li><a data-toggle="modal" data-target="#modal-shortcuts"><i class="fa fa-gear fa-fw"></i> Shorcuts</a>
                    </li>
                    <li class="divider"></li>
                    <li><a href="../public/login"><i class="fa fa-sign-out fa-fw"></i> Salir</a>
                    </li>
                </ul>
            </li>
        </ul>
        <div id="menu" class="navbar-default sidebar" role="navigation">
            <div class="sidebar-nav navbar-collapse">
                <ul class="nav" id="side-menu">
                    <li class="sidebar-search" style="background-color: #01579a;">
                        <h3 style="font-family: 'Jura', sans-serif;">
                          <a data-toggle="modal" data-target="#modal-about" style="color: white;font-size: 18px;"><i class="material-icons">widgets</i> <?= VERSION ?></a>
                        </h3>
                    </li>
                    <li>
                        <a href="./errorFactura"><i class="fa fa-dashboard fa-fw"></i> Inicio</a>
                    </li>
                    <li>
                        <a href="./errorFactura" target="_blank"><i class="fa fa-fw fa-chrome"></i> Nueva Pestaña</a>
                    </li>
                    <li>
                        <a href="../public/login"> <i class="fa fa-fw fa-sign-out" style="color:#ff0000"></i> Cerrar Sesión</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <div id="page-wrapper">
        <div class="row" id="cuerpo">
            <?php echo $this->layout()->content; ?>
        </div>
    </div>
</div>
<style>
    #loaderBootStrap1 {
  position: absolute;
  left: 50%;
  top: 50%;
  z-index: 1;
  width: 150px;
  height: 150px;
  margin: -75px 0 0 -75px;
  border: 16px solid #f3f3f3;
  border-radius: 50%;
  border-top: 16px solid rgb(233, 30, 99);
  width: 120px;
  height: 120px;
  -webkit-animation: spin 2s linear infinite;
  animation: spin 2s linear infinite;
}

@-webkit-keyframes spin {
  0% { -webkit-transform: rotate(0deg); }
  100% { -webkit-transform: rotate(360deg); }
}

@keyframes spin {
  0% { transform: rotate(0deg); }
  100% { transform: rotate(360deg); }
}
</style>
<div id="loaderBootStrap" class="modal fade" role="dialog">
    <div id="loaderBootStrap1"></div>
</div>
        <script type="text/javascript" src="../application/assets/bootstrap/js/bootstrap-multiselect.js"></script>
        <script type="text/javascript" src="../application/assets/bootstrap/js/jqBootstrapValidation.min.js" async=""></script>
        <script type="text/javascript" src="../application/assets/js/Chart.min.js"></script>
        <script type="text/javascript" src="../application/assets/js/moment.js"></script>        
        <script type="text/javascript" src="../application/assets/js/formatCurrency.js"></script>
        <script type="text/javascript" src="../application/assets/js/jquery.validate.js"></script>
        <script type="text/javascript" src="../application/assets/js/jquery-ui.js"></script>
        <script type="text/javascript" src="../application/assets/js/jquery.datatables-1.10.12.js"></script>
        <script type="text/javascript" src="../application/assets/js/buttons/js/dataTables.buttons.js"></script>
        <script type="text/javascript" src="../application/assets/js/buttons/js/buttons.html5.js"></script>
        <script type="text/javascript" src="../application/assets/js/JsBarcode128.js"></script>
        <script type="text/javascript" src="../application/assets/js/jquery.filtertable.js"></script>
        <script type="text/javascript" src="../application/assets/js/avance.js?v=10Thu"></script>
        <script type="text/javascript" src="../application/assets/js/jszip.js"></script>
        <script type="text/javascript" src="../application/assets/js/colResizable-1.6.js"></script>
        <script type="text/javascript" src="../application/assets/js/select2.js"></script>
        <script type="text/javascript" src="../application/assets/js/jquery.hotkey.min.js"></script>
        <script type="text/javascript" src="../application/assets/js/html2canvas.min.js"></script>
        <script type="text/javascript" src="../application/assets/bootstrap/js/bootstrap.min.js"></script>
        <script type="text/javascript" src="../application/assets/bootstrap/js/metisMenu.min.js"></script>
        <script type="text/javascript" src="../application/assets/bootstrap/js/sb-admin-2.js"></script>
        <script type="text/javascript" src="../application/assets/js/sweetalert2.js"></script>
</body>
</html>