<?php

 /**
 * 
 * esta clse esta diseñada con puras constantes diseñada para unificar toda constante que se usa dentro de InAX,
  * para migrar entre produccion o desarrollo basta con cambiar la contante config por el tipo de ambiente que se desee
  * en la base de datos el proceso debera ser manual ya que la clase que toma la decision acerca de el ambiente de desarrollo
  * o produccion en el archivo application.ini
 * @author Francisco Delgado <packo6300@gmail.com>
 */

(CONFIG==DESARROLLO) ? define('INTERNA','INTERNA2.INTERNA') : define('INTERNA','INTERNA');
define("COMPANY",$_SESSION['company']); 
define("IMAGEN_PDF",__DIR__."/../../../assets/img"); 
define("VERSION", "inAX Versión: 2.3");
//define('WEB_SERVICE_URL', WSDL.'.xml');
define('WEB_SERVICE_URL', 'http://' . CONFIG . '/MicrosoftDynamicsAXAif60/STFSalesOrderWebService/xppservice.svc?wsdl');
define('WEB_SERVICE_INVOICE_URL', 'http://' . CONFIG . '/MicrosoftDynamicsAXAif60/STFWSInvoicePayment/xppservice.svc?wsdl');
define('PERIODO_DE_VENTA',1); 
define("MESSAGE","VERSION DE ".ACTUAL." (LAS COTIZACIONES GENERADAS AQUI NO SON VALIDAS) FAVOR DE HACER OBSERVACIONES A DEPARTAMENTO DE DESARROLLO al correo sistemas10@avanceytec.com.mx TRABAJANDO EN: ".CONFIG);
$sucursal=explode(".",filter_var($_SERVER['REMOTE_ADDR']));
$v=count($sucursal);
($v>1) ? define('SUCURSAL',filter_var($sucursal[2]))  : define('SUCURSAL',1);
define("ANSI_NULLS", "SET ANSI_NULLS ON");
define("ANSI_WARNINGS","SET ANSI_WARNINGS ON");
define("DATA_SUCURSAL","select * from ".INTERNA.".dbo.sucursal where idsuc= :id;");
define("GET_PROPOSITO", "SELECT name, T0.RECID AS id,type , T1.DESCRIPTION FROM LOGISTICSLOCATIONROLE T0 INNER JOIN LOGISTICSLOCATIONROLETRANSLATION T1 ON (T1.LOCATIONROLE = T0.RECID) WHERE T0.ISPOSTALADDRESS=1  AND T1.LANGUAGEID = 'es' and T0.ispostaladdress=1");
define("GET_ZIP_CODE", "SELECT t1.ZIPCODE,t1.COUNTRYREGIONID,t1.STATE,t1.RECID,t2.shortname AS pais ,t3.name AS estado FROM LOGISTICSADDRESSZIPCODE t1 INNER JOIN LOGISTICSADDRESSCOUNTRYREGIONTRANSLATION t2 ON t2.COUNTRYREGIONID = t1.COUNTRYREGIONID  INNER JOIN LOGISTICSADDRESSSTATE t3 ON t3.stateid = t1.state WHERE t1.zipcode= ? AND t2.LANGUAGEID='es'");
define("GET_CUIDAD", "SELECT name,stateid, recid AS id FROM LOGISTICSADDRESSSCITY WHERE stateid= ? ;");
define("GET_ESTADOS", "SELECT name, stateid, recid AS id FROM LOGISTICSADDRESSSTATE WHERE countryregionid=?;");
define("GET_COLONIA", "SELECT countryregionid, stateid, countyid, name, recid AS id FROM LOGISTICSADDRESSCOUNTY WHERE stateid=? ");
define("GET_PAIS", "SELECT longname,countryregionid,recid AS id FROM LOGISTICSADDRESSCOUNTRYREGIONTRANSLATION WHERE languageid='es' ORDER BY CASE WHEN countryregionid = 'MEX' THEN 1 ELSE 2 END");
define("GET_DESCUENTO", "SELECT groupid,name,recid AS id FROM PriceDiscGroup WHERE dataareaid='".COMPANY."' ORDER BY (CASE WHEN groupid LIKE ? THEN 0 ELSE 1 END) ");
define("GET_ALMACEN", "SELECT inventlocationid, name, recid AS id FROM inventlocation WHERE dataareaid='".COMPANY."' AND inventlocationid LIKE ? ");
define("GET_ZONA_VENTA", "SELECT salesdistrictid, description, recid AS id FROM SMMBUSRELSALESDISTRICTGROUP WHERE DATAAREAID = '".COMPANY."';");
define("GET_SITIO_VENTA", "SELECT siteid,name,recid AS id FROM INVENTSITE WHERE dataareaid='".COMPANY."'");
define("GET_MONEDA", "SELECT currencycode, txt AS moneda , recid AS id FROM currency ORDER BY CASE WHEN CURRENCYCODE = 'MXN' THEN 1 ELSE 2 END");
define("GET_CONJUNTO_CLIENTES", "SELECT custgroup,name,recid as id FROM CUSTGROUP WHERE dataareaid='".COMPANY."'");
define("ORIGEN_VENTA", "select ORIGINID , DESCRIPTION from dbo.SALESORIGIN where DATAAREAID ='".COMPANY."' group by ORIGINID,DESCRIPTION;");
define("SITIOS", "SELECT T0.SITEID,T0.NAME FROM INVENTSITE T0 WHERE T0.SITEID !='CEDSCHI' AND DATAAREAID=? ;");
define("GET_ITEMS_NOT_BLOKED","select T0.ITEMID from INVENTITEMGROUPITEM T0 right join INVENTITEMGROUP T1 on T0.ITEMGROUPID=T1.ITEMGROUPID and T1.DATAAREAID='".COMPANY."' where T0.ITEMDATAAREAID='".COMPANY."' and T1.BLOCKSALESPRICES=0 and T1.ITEMGROUPID ='PRENDAS'");
define("GET_ITEMS2","SELECT T0.ITEMID AS value,T1.NAME as label FROM INVENTTABLE T0 INNER JOIN ECORESPRODUCTTRANSLATION T1 ON T0.PRODUCT=T1.PRODUCT INNER JOIN INVENTTABLEMODULE T2 ON T0.ITEMID=T2.ITEMID INNER JOIN INVENTITEMGROUPITEM T3 ON T0.ITEMID=T3.ITEMID AND T3.ITEMDATAAREAID='".COMPANY."' INNER JOIN INVENTITEMGROUP T4 ON T3.ITEMGROUPID=T4.ITEMGROUPID AND T4.DATAAREAID='".COMPANY."' WHERE T0.DATAAREAID='".COMPANY."' AND T2.DATAAREAID = '".COMPANY."' AND T2.MODULETYPE='2' ORDER BY value;");
define("GET_ITEMS_COMMON","select ITEMID as value, EXTERNALITEMTXT as label from CustVendExternalItem order by value;");
define("GET_PRODUCT_DETAIL", "SELECT T1.NAME as label,T2.UNITID as unidad,T4.BLOCKSALESPRICES as PrecioBloqueado FROM INVENTTABLE T0 INNER JOIN ECORESPRODUCTTRANSLATION T1 ON T0.PRODUCT=T1.PRODUCT INNER JOIN INVENTTABLEMODULE T2 ON T0.ITEMID=T2.ITEMID INNER JOIN INVENTITEMGROUPITEM T3 ON T0.ITEMID=T3.ITEMID AND T3.ITEMDATAAREAID='".COMPANY."' INNER JOIN INVENTITEMGROUP T4 ON T3.ITEMGROUPID=T4.ITEMGROUPID AND T4.DATAAREAID='".COMPANY."' WHERE T0.DATAAREAID='".COMPANY."' AND T2.DATAAREAID = '".COMPANY."' AND T2.MODULETYPE='2' and T0.ITEMID= ? ORDER BY label;");
define("GET_ARTICULOS","SELECT CONCAT(T0.ITEMID,' - ',T1.NAME) AS label,T0.ITEMID AS value FROM INVENTTABLE T0 INNER JOIN ECORESPRODUCTTRANSLATION T1 ON T0.PRODUCT=T1.PRODUCT INNER JOIN INVENTTABLEMODULE T2 ON T0.ITEMID=T2.ITEMID INNER JOIN INVENTITEMGROUPITEM T3 ON T0.ITEMID=T3.ITEMID AND T3.ITEMDATAAREAID='".COMPANY."' INNER JOIN INVENTITEMGROUP T4 ON T3.ITEMGROUPID=T4.ITEMGROUPID AND T4.DATAAREAID='".COMPANY."' WHERE T0.DATAAREAID='".COMPANY."' AND T2.DATAAREAID = '".COMPANY."' AND T2.MODULETYPE='2' ORDER BY CONCAT(T0.ITEMID,' - ',T1.NAME);");
define('CLIENTES_INICIAL', "SELECT DISTINCT T0.accountnum 'ClaveCliente',T1.NAME 'Nombre' FROM custtable T0 INNER JOIN dirpartytable T1 ON T0.party = T1.recid LEFT JOIN logisticslocation T2 ON T1.primaryaddresslocation = T2.recid AND T2.ispostaladdress = '1' LEFT JOIN logisticspostaladdress T3 ON T2.recid = T3.location AND Dateadd(hour, -7, T3.validfrom) < Getdate() AND T3.validto > Getdate() where DATAAREAID='".COMPANY."';");
define("CLIENTE_POR_CODIGO", "SELECT T0.ACCOUNTNUM 'ClaveCliente', T1.NAME 'Nombre', ISNULL(T3.ADDRESS,'Sin Dirección') 'Direccion', T3.RECID 'RecIdDireccion', T0.INVENTSITEID 'Sitio', T0.INVENTLOCATION 'Almacen', CASE WHEN T0.DLVTERM='' THEN 'CONTADO' ELSE T0.DLVTERM END 'CondEntrega', T0.PAYMMODE 'MetodoPago', CASE T0.BLOCKED WHEN '0' THEN 'No' WHEN '1' THEN 'Factura' WHEN '2' THEN 'Todo' END AS 'Bloqueo', T0.BANKACCOUNT 'CuentaBanco', T0.DLVMODE 'ModoEntrega',T0.PAYMTERMID FROM CUSTTABLE T0 INNER JOIN DIRPARTYTABLE T1 ON T0.PARTY=T1.RECID LEFT JOIN LOGISTICSLOCATION T2 ON T1.PRIMARYADDRESSLOCATION=T2.RECID AND T2.ISPOSTALADDRESS='1' LEFT JOIN LOGISTICSPOSTALADDRESS T3 ON T2.RECID=T3.LOCATION AND DATEADD(HOUR,-7,T3.VALIDFROM)<GETDATE() AND T3.VALIDTO>GETDATE() WHERE T0.ACCOUNTNUM = ?;");
define("VERIFICA_RFC","select TOP 1 * FROM CUSTTABLE where RFC_MX= ? and  DATAAREAID= ?  ");
define("SITIO_FILTRO", "SELECT T0.INVENTLOCATIONID FROM INVENTLOCATION T0 WHERE LEFT(T0.INVENTLOCATIONID,4) = ? AND T0.INVENTLOCATIONID NOT LIKE '%TRAS' AND DATAAREAID='".COMPANY."'");
define('QUERY_CARGOS', "SELECT T0.PaymMode,T0.STF_PercentageCharges,T0.NAME FROM CustPaymModeTable T0 WHERE T0.PAYMMODE IN ('01','02','03','04','28','99') AND DATAAREAID = '".COMPANY."' ORDER BY T0.PAYMMODE;");
define("QUERY_REMISION2","SELECT T0.PACKINGSLIPID 'Remision',T0.SALESID 'OrdenVenta',(SELECT  DIRP.NAME FROM DIRPARTYTABLE DIRP	WHERE DIRP.RECID = ( SELECT PARTY FROM CUSTTABLE WHERE ACCOUNTNUM = T9.CUSTACCOUNT )) 'Cliente',CONVERT(VARCHAR,DATEADD(HOUR,-7, T0.CREATEDDATETIME),103) 'FechaCreacion', T5.ADDRESS 'DireccionEnvio', T6.ADDRESS 'DireccionFacturacion', T0.DLVMODE 'ModoEntrega', T0.DLVTERM 'CondicionesEntrega', T3.NAME 'Vendedor', T1.ITEMID 'ClaveArticulo',T1.NAME 'Articulo', CASE WHEN (convert(decimal(16, 2), T7.QTY)) > 0 THEN convert(decimal(16, 2),T7.QTY ) ELSE (convert( decimal(16, 2), T7.QTY)) * -1 END 'Pedido',convert(decimal(16, 2),T1.QTY) 'Cantidad',convert(decimal(16, 2),T1.PDSCWREMAIN) 'Restante',T1.SALESUNIT 'Unidad', ISNULL((T8.INVENTSITEID),T0.PRINTMGMTSITEID ) 'Sitio',ISNULL((T8.INVENTLOCATIONID), T0.INVENTLOCATIONID) 'Almacen',ISNULL((T8.INVENTBATCHID),'') 'Lote',ISNULL(T9.STF_OBSERVATIONS, '') 'Comentarios', T9.CUSTOMERREF 'ReferenciaCliente', T9.PURCHORDERFORMNUM 'OrdendeCliente',(SELECT NAME FROM INVENTSITE WHERE SITEID = T8.INVENTSITEID AND DATAAREAID = '".COMPANY."' ) 'SitioNombre', (SELECT  OBSERVATIONS FROM SALESTABLE WHERE  SALESID = T9.SALESID AND DATAAREAID = '".COMPANY."') AS comentarioCabecera FROM CUSTPACKINGSLIPJOUR T0 INNER JOIN CUSTPACKINGSLIPTRANS T1 ON T0.PACKINGSLIPID = T1.PACKINGSLIPID AND	T0.DATAAREAID = '".COMPANY."' INNER JOIN HCMWORKER T2 ON T0.WORKERSALESTAKER = T2.RECID AND	T1.DATAAREAID = '".COMPANY."'  INNER JOIN DIRPARTYTABLE T3 ON T2.PERSON = T3.RECID LEFT JOIN LOGISTICSPOSTALADDRESS T5 ON T5.RECID = T0.DELIVERYPOSTALADDRESS  LEFT JOIN LOGISTICSPOSTALADDRESS T6 ON T6.RECID = T0.INVOICEPOSTALADDRESS LEFT JOIN INVENTTRANSORIGIN T4 ON T1.INVENTTRANSID = T4.INVENTTRANSID AND	T4.DATAAREAID = '".COMPANY."' LEFT JOIN INVENTTRANS T7 ON T4.RECID = T7.INVENTTRANSORIGIN  AND	T7.DATAAREAID = '".COMPANY."' LEFT JOIN INVENTDIM T8 ON T7.INVENTDIMID = T8.INVENTDIMID  AND T8.DATAAREAID = '".COMPANY."' INNER JOIN SALESLINE T9 ON (	T1.SALESID = T9.SALESID	AND T1.ITEMID = T9.ITEMID AND T1.INVENTTRANSID = T9.INVENTTRANSID AND T9.DATAAREAID = '".COMPANY."' ) WHERE	T0.PACKINGSLIPID = ? ORDER BY	T1.LINENUM ");
define('QUERY_REMISION', "SELECT T0.PACKINGSLIPID 'Remision',T0.SALESID 'OrdenVenta',(SELECT DIRP.NAME FROM DIRPARTYTABLE DIRP WHERE DIRP.RECID = (SELECT PARTY FROM CUSTTABLE WHERE ACCOUNTNUM = T9.CUSTACCOUNT)) 'Cliente', CONVERT(VARCHAR,DATEADD(HOUR,-7,T0.CREATEDDATETIME),103) 'FechaCreacion',T5.ADDRESS 'DireccionEnvio', T6.ADDRESS 'DireccionFacturacion', T0.DLVMODE 'ModoEntrega', T0.DLVTERM 'CondicionesEntrega', T3.NAME 'Vendedor', T1.ITEMID 'ClaveArticulo', T1.NAME 'Articulo', CASE WHEN (convert(decimal(16,2),T7.QTY)) > 0 THEN convert(decimal(16,2),T7.QTY) ELSE (convert(decimal(16,2),T7.QTY)) * -1 END 'Pedido',convert(decimal(16,2),T1.QTY) 'Cantidad', convert(decimal(16,2),T1.PDSCWREMAIN) 'Restante', T1.SALESUNIT 'Unidad', ISNULL((T8.INVENTSITEID),T0.PRINTMGMTSITEID) 'Sitio', ISNULL((T8.INVENTLOCATIONID),T0.INVENTLOCATIONID) 'Almacen', ISNULL((T8.INVENTBATCHID),'') 'Lote', ISNULL(T9.STF_OBSERVATIONS,'') 'Comentarios', T9.CUSTOMERREF 'ReferenciaCliente', T9.PURCHORDERFORMNUM 'OrdendeCliente',(SELECT NAME FROM INVENTSITE WHERE SITEID = T8.INVENTSITEID AND DATAAREAID = '".COMPANY."') 'SitioNombre', (SELECT OBSERVATIONS FROM SALESTABLE WHERE SALESID = T9.SALESID AND DATAAREAID = '".COMPANY."') AS comentarioCabecera FROM CUSTPACKINGSLIPJOUR T0 INNER JOIN CUSTPACKINGSLIPTRANS T1 ON T0.PACKINGSLIPID=T1.PACKINGSLIPID INNER JOIN HCMWORKER T2 ON T0.WORKERSALESTAKER=T2.RECID INNER JOIN DIRPARTYTABLE T3 ON T2.PERSON=T3.RECID LEFT JOIN LOGISTICSPOSTALADDRESS T5 ON T5.RECID=T0.DELIVERYPOSTALADDRESS LEFT JOIN LOGISTICSPOSTALADDRESS T6 ON T6.RECID=T0.INVOICEPOSTALADDRESS LEFT JOIN INVENTTRANSORIGIN T4 ON T1.INVENTTRANSID=T4.INVENTTRANSID LEFT JOIN INVENTTRANS T7 ON T4.RECID=T7.INVENTTRANSORIGIN LEFT JOIN INVENTDIM T8 ON T7.INVENTDIMID=T8.INVENTDIMID INNER JOIN SALESLINE T9 ON (T1.SALESID=T9.SALESID AND T1.ITEMID=T9.ITEMID AND T1.INVENTTRANSID = T9.INVENTTRANSID) WHERE T0.PACKINGSLIPID = ? ORDER BY T1.ITEMID;");
define('QUERY_COTIZACION', "SELECT 
       T1.quotationid 'Cotizacion', 
       CONVERT(VARCHAR(10), CONVERT(DATE, T0.receiptdaterequested, 106), 103) 'Fecha', 
       CONVERT(VARCHAR(10), CONVERT(DATE, T0.quotationexpirydate, 106), 103) 'FechaVencimiento', 
       T0.payment 'Pago', 
       T0.deliveryname 'NombreEntrega', 
       (SELECT TA.[address] 
        FROM   logisticspostaladdressview TA 
        WHERE  TA.recid = T0.deliverypostaladdress) 'DireccionEntrega', 
       T1.itemid 'CodigoArticulo', 
       T1.NAME 'DescripcionArticulo', 
       CONVERT(DECIMAL(16, 2), T1.salesqty) 'Cantidad', 
       T0.currencycode 'Moneda', 
       T1.salesunit 'Unidad', 
       CONVERT(DECIMAL(16, 2), ( T1.salesprice ) * ( 1 + ( 
                               Isnull(T4.value, 0) / 100 ) 
                                                   ) * 
                               ( 1 - ( T1.linepercent / 100 ) )) 'PrecioUnitario', 
       CONVERT(DECIMAL(16, 2), ( T1.salesprice * T1.salesqty ) * ( 1 + ( 
                               Isnull(T4.value, 0) / 100 ) ) 
                               * ( 1 
                               - ( T1.linepercent / 100 ) )) 'Importe', 
       T2.inventsiteid 'Sitio', 
       T2.inventlocationid 'Almacen', 
       CONVERT(DECIMAL(16, 2), ( T1.salesprice * T1.salesqty ) * ( 1 + ( 
                               Isnull(T4.value, 0) / 100 ) ) 
                               * ( 1 
                               - ( T1.linepercent / 100 ) )) 'Subtotal', 
       CONVERT(DECIMAL(16, 2), ( ( T1.salesprice * T1.salesqty ) * ( 1 + ( 
                                 Isnull(T4.value, 0) / 100 ) 
                                 ) * ( 1 
                                                         - ( 
                                       T1.linepercent / 100 ) ) ) 
                               * .16) 'iva', 
       CONVERT(DECIMAL(16, 2), ( ( T1.salesprice * T1.salesqty ) * ( 1 + ( 
                                 Isnull(T4.value, 0) / 100 ) 
                                 ) * ( 1 
                                                         - ( 
                                       T1.linepercent / 100 ) ) ) 
                               * 1.16) 'Total', 
       T0.workersalestaker AS 'idVend', 
       T1.stf_observations AS 'ComentarioLinea', 
       (SELECT TDIRP.NAME 
        FROM   dirpartytable TDIRP 
               INNER JOIN hcmworker HCMW 
                       ON ( TDIRP.recid = HCMW.person ) 
        WHERE  HCMW.recid = T0.workersalestaker) AS 'Vendedor', 
       T3.exchangerate 
FROM   salesquotationtable T0 
       LEFT JOIN salesquotationline T1 ON T0.quotationid = T1.quotationid 
       LEFT JOIN inventdim T2 ON T1.inventdimid = T2.inventdimid AND T2.dataareaid = '".COMPANY."' 
       LEFT JOIN exchangerate T3 ON T3.validfrom = T0.receiptdaterequested 
       LEFT JOIN markuptrans T4 ON ( T4.transrecid = T0.recid AND T4.dataareaid = '".COMPANY."' AND T4.transtableid = ( SELECT TOP 1 transtableid 
        FROM   markuptrans TX 
        WHERE  TX.transrecid = T0.recid 
        ORDER  BY TX.createddatetime DESC) ) 
WHERE  T0.quotationid = ?
ORDER  BY T1.stf_observations ASC;");
define('QUERY_COTIZACION_2', "SELECT T0.QUOTATIONID, ISNULL(T1.STREET,'NoDef') AS CALLE, ISNULL(T2.NAME,'NoDef') AS COLONIA, ISNULL(T1.CITY,'NoDef') AS CIUDAD, ISNULL(T3.NAME,'NoDef') AS ESTADO
    , ISNULL(T4.SHORTNAME,'NoDef') AS PAIS , ISNULL(T1.ZIPCODE,'NoDef') AS ZIPCODE FROM SALESQUOTATIONTABLE T0 LEFT JOIN LOGISTICSPOSTALADDRESS T1 ON (T1.RECID = T0.DELIVERYPOSTALADDRESS)
    LEFT JOIN LOGISTICSADDRESSCOUNTY T2 ON (T2.COUNTYID = T1.COUNTY and T2.STATEID=T1.STATE) LEFT JOIN LOGISTICSADDRESSSTATE T3 ON (T3.STATEID = T1.STATE) LEFT JOIN LOGISTICSADDRESSCOUNTRYREGIONNAMEVIEW T4 ON (T4.COUNTRYREGIONID = T1.COUNTRYREGIONID AND T4.LANGUAGEID = 'es') WHERE T0.QUOTATIONID = ?;");
define("USUARIO_TO_ID", "SELECT DBO.getRecidDynamicUser( ? ) AS recidUsuario;");
define("EDITAR_OV", "SELECT T0.SALESID,T0.CUSTACCOUNT,T0.SALESNAME,T0.DELIVERYPOSTALADDRESS,T0.INVENTSITEID 'SitioEnc',T0.INVENTLOCATIONID 'AlmacenEnc',T0.CURRENCYCODE,T0.DLVMODE,T0.DLVTERM,
    T0.PAYMMODE,ISNULL(T7.STF_PERCENTAGECHARGES,0) 'STF_PERCENTAGECHARGES',T6.NAME 'Vendedor',T0.WORKERSALESRESPONSIBLE, T0.WORKERSALESTAKER,T2.ADDRESS,T1.ITEMID,T1.NAME,T1.SALESQTY,T1.SALESUNIT,T4.INVENTSITEID,T4.INVENTLOCATIONID,T4.INVENTBATCHID,T4.WMSLOCATIONID
    FROM SALESTABLE T0 LEFT JOIN SALESLINE T1 ON T0.SALESID=T1.SALESID LEFT JOIN LOGISTICSPOSTALADDRESSVIEW T2 ON T0.DELIVERYPOSTALADDRESS=T2.POSTALADDRESSRECID INNER JOIN CUSTTABLE T3 ON T0.CUSTACCOUNT=T3.ACCOUNTNUM LEFT JOIN INVENTDIM T4 ON T1.INVENTDIMID=T4.INVENTDIMID INNER JOIN HCMWORKER T5 ON T0.WORKERSALESRESPONSIBLE=T5.RECID INNER JOIN DIRPARTYTABLE T6 ON T5.PERSON=T6.RECID LEFT JOIN CUSTPAYMMODETABLE T7 ON T0.PAYMMODE=T7.PAYMMODE WHERE T0.SALESID = ?;");
define("FORMA_ENTREGA", "SELECT T0.CODE,T0.TXT FROM DLVMODE T0 WHERE T0.DATAAREAID='".COMPANY."'");
define("ETIQUETA", "SELECT T5.RECID,(CASE T6.NAME WHEN 'Business' THEN 'Negocio' WHEN 'Delivery' THEN 'Entrega' WHEN 'Fixed asset' THEN 'Activo Fijo' WHEN 'Home' THEN 'Particular' WHEN 'Other' THEN 'Otros' WHEN 'Invoice' THEN 'Facturacion' WHEN 'Payment' THEN 'Pago' WHEN 'Remit to' THEN 'Remitir a' WHEN 'Service' THEN 'Servicio' WHEN 'Third party shipping' THEN 'Direccion de envio a terceros' ELSE T6.NAME END) AS 'PROPOSITO' FROM CUSTTABLE T0 INNER JOIN DIRPARTYTABLE T1 ON T0.PARTY=T1.RECID INNER JOIN DIRPARTYLOCATION T2 ON T2.PARTY=T1.RECID INNER JOIN LOGISTICSLOCATION T3 ON T2.LOCATION=T3.RECID
        INNER JOIN DIRPARTYLOCATIONROLE T4 ON T4.PARTYLOCATION=T2.RECID INNER JOIN LOGISTICSPOSTALADDRESS T5 ON T5.LOCATION=T3.RECID AND T5.VALIDTO >= GETDATE() INNER JOIN LOGISTICSLOCATIONROLE T6 ON T4.LOCATIONROLE=T6.RECID WHERE T0.ACCOUNTNUM = ? GROUP BY T0.ACCOUNTNUM,T5.[ADDRESS],T5.RECID,T3.DESCRIPTION,T2.ISPRIMARY,T0.PARTY,T6.NAME ORDER BY T2.ISPRIMARY DESC;");
define("GET_ORGANIZACION", "SELECT top 10 name, partynumber, recid AS id FROM dirpartytable");
define("TIPO_CAMBIO", "SELECT CHAR(36)+ISNULL(CONVERT(VARCHAR(MAX),CONVERT(DECIMAL(10,2),(EXC.EXCHANGERATE/100)))+' MXN',(SELECT TOP 1 CONVERT(VARCHAR(MAX),(CONVERT(DECIMAL(10,2),EXC.EXCHANGERATE/100))) + ' MXN T.C. anterior' 
            FROM EXCHANGERATE EXC WHERE EXC.VALIDFROM = (SELECT MAX(EXC1.VALIDFROM) FROM EXCHANGERATE EXC1))) AS tipoCambio FROM (SELECT 1 dummy) dummy LEFT JOIN EXCHANGERATE EXC ON ( CONVERT(VARCHAR(10),EXC.VALIDFROM,120) = CONVERT(VARCHAR(10),GETDATE(),120) );");
define("INICIO_CLVECLTE", "SELECT T0.ACCOUNTNUM,T0.RFC_MX,ISNULL((SELECT TA.LOCATOR FROM LOGISTICSELECTRONICADDRESS TA WHERE TA.RECID=T1.PRIMARYCONTACTPHONE),'No Definido') 'Telefono',
                        ISNULL((SELECT TA.LOCATOR FROM LOGISTICSELECTRONICADDRESS TA WHERE TA.RECID=T1.PRIMARYCONTACTEMAIL),'No Definido') 'Correo' FROM CUSTTABLE T0 INNER JOIN DIRPARTYTABLE T1 ON T0.PARTY=T1.RECID WHERE T0.ACCOUNTNUM = ? ;");
define("INICIO_CLVECLTE_DETALLE", "SELECT T0.ACCOUNTNUM,T3.DESCRIPTION,T5.ADDRESS,T5.RECID, STUFF((SELECT ',' + (SELECT CASE T16.NAME WHEN 'Business' THEN 'Negocio' WHEN 'Delivery' THEN 'Entrega' WHEN 'Fixed asset' THEN 'Activo Fijo' WHEN 'Home' THEN 'Particular'  WHEN 'Other' THEN 'Otros' WHEN 'Invoice' THEN 'Facturacion' WHEN 'Payment' THEN 'Pago'
     WHEN 'Remit to' THEN 'Remitir a' WHEN 'Service' THEN 'Servicio' WHEN 'Third party shipping' THEN 'Direccion de envio a terceros' ELSE T16.NAME END) FROM DIRPARTYTABLE T11 INNER JOIN DIRPARTYLOCATION T12 ON T12.PARTY=T11.RECID INNER JOIN LOGISTICSLOCATION T13 ON T12.LOCATION=T13.RECID INNER JOIN DIRPARTYLOCATIONROLE T14 ON T14.PARTYLOCATION=T12.RECID
     INNER JOIN LOGISTICSPOSTALADDRESS T15 ON T15.LOCATION=T13.RECID AND T15.VALIDTO >= GETDATE() INNER JOIN LOGISTICSLOCATIONROLE T16 ON T14.LOCATIONROLE=T16.RECID WHERE T5.[ADDRESS]=T15.[ADDRESS] AND T11.RECID=T0.PARTY FOR XML PATH('')),1,1,'') as 'Proposito', T2.ISPRIMARY AS flagInvoice FROM CUSTTABLE T0
     INNER JOIN DIRPARTYTABLE T1 ON T0.PARTY=T1.RECID INNER JOIN DIRPARTYLOCATION T2 ON T2.PARTY=T1.RECID INNER JOIN LOGISTICSLOCATION T3 ON T2.LOCATION=T3.RECID INNER JOIN DIRPARTYLOCATIONROLE T4 ON T4.PARTYLOCATION=T2.RECID INNER JOIN LOGISTICSPOSTALADDRESS T5 ON T5.LOCATION=T3.RECID AND T5.VALIDTO >= GETDATE()
     INNER JOIN LOGISTICSLOCATIONROLE T6 ON T4.LOCATIONROLE=T6.RECID WHERE T0.ACCOUNTNUM = ? GROUP BY T0.ACCOUNTNUM,T5.[ADDRESS],T5.RECID,T3.DESCRIPTION,T2.ISPRIMARY,T0.PARTY ORDER BY T2.ISPRIMARY DESC;");

define("IS_PRICE_BLOKED", "SELECT T0.ITEMID,T1.BLOCKSALESPRICES FROM INVENTITEMGROUPITEM T0 INNER JOIN INVENTITEMGROUP T1 ON T0.ITEMGROUPID=T1.ITEMGROUPID AND T0.ITEMGROUPDATAAREAID='".COMPANY."' AND T1.DATAAREAID = '".COMPANY."' WHERE T0.ITEMID = ?; ");
define("INICIO_COTIZACION", "SELECT DISTINCT SALES.CUSTACCOUNT,T5.RECID,SALES.CURRENCYCODE ,SALES.INVENTSITEID,SALES.INVENTLOCATIONID,SALES.PAYMMODE ,SALES.DLVMODE,SALES.DLVTERM,SALES.WORKERSALESTAKER,SALES.WORKERSALESRESPONSIBLE
            ,SALES.CUSTOMERREF,SALES.CUSTPURCHASEORDER,SALES.STF_OBSERVATIONS,ISNULL((SELECT T1.STF_PERCENTAGECHARGES FROM CUSTPAYMMODETABLE T1 WHERE T1.PAYMMODE = SALES.PAYMMODE AND DATAAREAID = '".COMPANY."'),0) AS CARGO
            FROM SALESQUOTATIONTABLE SALES INNER JOIN CUSTTABLE CUST ON (CUST.ACCOUNTNUM = SALES.CUSTACCOUNT) INNER JOIN DIRPARTYTABLE T1 ON CUST.PARTY=T1.RECID LEFT JOIN DIRPARTYLOCATION T2 ON T2.PARTY=T1.RECID
            LEFT JOIN LOGISTICSLOCATION T3 ON T2.LOCATION=T3.RECID LEFT JOIN DIRPARTYLOCATIONROLE T4 ON T4.PARTYLOCATION=T2.RECID LEFT JOIN LOGISTICSLOCATIONROLE T6 ON T6.RECID = T4.LOCATIONROLE LEFT JOIN LOGISTICSPOSTALADDRESS T5 ON T5.LOCATION=T3.RECID AND T5.VALIDTO >= GETDATE()
            WHERE QUOTATIONID = ?  AND (T2.ISPRIMARY != '') AND T5.RECID IS NOT NULL;");
define("INICIO_COTIZACION_2", "SELECT LINES.ITEMID,LINES.CUSTACCOUNT ,INVDIM.INVENTSITEID,INVDIM.INVENTLOCATIONID,INVDIM.WMSLOCATIONID,'' INVENTBATCHID,LINES.SALESQTY ,LINES.STF_SALESPRICE AS SALESPRICE ,LINES.STF_OBSERVATIONS,LINES.CURRENCYCODE FROM SALESQUOTATIONLINE LINES INNER JOIN SALESQUOTATIONTABLE SALES ON SALES.QUOTATIONID = LINES.QUOTATIONID INNER JOIN INVENTDIM INVDIM ON INVDIM.INVENTDIMID = LINES.INVENTDIMID WHERE LINES.QUOTATIONID = ?;");
define("DELETE_COTIZACION", "DELETE FROM ".INTERNA.".DBO.tablaTodasCot WHERE idCotizacion = ?;");
define("ORDVTA", "SELECT SALES.LINENUM,SALES.SALESID,SALES.ITEMID,SALES.NAME,SALES.QTYORDERED,SALES.SALESUNIT FROM SALESLINE SALES WHERE SALES.SALESID = ? ORDER BY SALES.LINENUM;");
define("CTZN", "SELECT COTI.LINENUM,COTI.QUOTATIONID AS 'SALESID',COTI.ITEMID,COTI.NAME,COTI.QTYORDERED,COTI.SALESUNIT FROM SALESQUOTATIONLINE COTI WHERE COTI.QUOTATIONID = ? ORDER BY COTI.LINENUM;");
define("ORDVTADET","SELECT SALES.LINENUM,SALES.SALESID,SALES.ITEMID,SALES.NAME,SALES.QTYORDERED,SALES.SALESUNIT, SUM(INVSUM.AVAILPHYSICAL) FisicaDisponible FROM SALESLINE SALES 
                            INNER JOIN INVENTSUM INVSUM ON (INVSUM.ITEMID = SALES.ITEMID) INNER JOIN INVENTDIM INVDIM ON (INVDIM.INVENTDIMID = INVSUM.INVENTDIMID)
                            WHERE SALES.SALESID = '?' AND INVDIM.INVENTSITEID= '?' AND INVDIM.INVENTLOCATIONID LIKE '%CONS' GROUP BY SALES.LINENUM,SALES.SALESID,SALES.ITEMID,SALES.NAME,SALES.QTYORDERED,SALES.SALESUNIT;");
define("KARDEX_FILTER","select t1.id_kardex,t1.usuario,t1.nombre,t1.fecha,t1.movimiento,t2.nombre as sucursal from  ".INTERNA.".dbo.kardex t1 right join ".INTERNA.".dbo.sucursal t2 on t2.idsuc=t1.sucursal where t1.id_kardex like '?%' and t1.usuario like '%?%' and t1.nombre like '%?%' and t1.fecha between '?' and '?' and t1.movimiento like '%?%' and t2.nombre like '%?%'  order by t1.fecha desc;");
define("KARDEX","select TOP 250 * from ".INTERNA.".dbo.kardex order by fecha desc;");
define("GET_COTIZACION_CLIENT_DATA","SELECT PAYMMODE,INVENTSITEID,INVENTLOCATIONID,CURRENCYCODE,DLVMODE,DLVTERM, WORKERSALESTAKER,WORKERSALESRESPONSIBLE,STF_OBSERVATIONS,CUSTOMERREF,CUSTPURCHASEORDER,CUSTACCOUNT, ISNULL((SELECT T1.STF_PERCENTAGECHARGES FROM CUSTPAYMMODETABLE T1 WHERE T1.PAYMMODE = T0.PAYMMODE AND DATAAREAID = '".COMPANY."'),0) AS CARGO,ISNULL( ( SELECT mov_Card_Num FROM ".INTERNA.".DBO.inaxmovs WHERE mov_id = ? ),'0000') AS BANKACCOUNT, T0.PAYMENT FROM SALESQUOTATIONTABLE T0 WHERE T0.QUOTATIONID = ? ;");
/*pendiente modificar query para regresar precio con cargos*/
define("GET_COTIZACION_CONTENT_DATA", "SELECT T0.ITEMID,T0.NAME,T0.SALESUNIT,T0.SALESQTY,T0.STF_SALESPRICE,T1.INVENTSITEID,T1.INVENTLOCATIONID,'0' AS CAMBIOWS , '0' AS PRECIOWS,T0.CURRENCYCODE,T0.STF_OBSERVATIONS,T3.BLOCKSALESPRICES FROM SALESQUOTATIONLINE T0 INNER JOIN INVENTDIM T1 ON (T1.INVENTDIMID = T0.INVENTDIMID) INNER JOIN INVENTITEMGROUPITEM T2 ON (T2.ITEMID = T0.ITEMID AND T2.ITEMGROUPDATAAREAID = '".COMPANY."')  INNER JOIN INVENTITEMGROUP T3 ON (T3.ITEMGROUPID = T2.ITEMGROUPID AND T3.DATAAREAID = '".COMPANY."') WHERE T0.QUOTATIONID = ? ORDER BY T0.LINENUM;");
define("EDITAR_ORDEN_VENTA", "SELECT PAYMMODE,INVENTSITEID,INVENTLOCATIONID,CURRENCYCODE,DLVMODE,DLVTERM,CUSTACCOUNT, ISNULL((SELECT T1.STF_PERCENTAGECHARGES FROM CUSTPAYMMODETABLE T1 WHERE T1.PAYMMODE = T0.PAYMMODE AND DATAAREAID = '".COMPANY."'),0) AS CARGO,WORKERSALESTAKER,WORKERSALESRESPONSIBLE, T0.OBSERVATIONS AS STF_OBSERVATIONS, T0.CUSTOMERREF,T0.PURCHORDERFORMNUM AS CUSTPURCHASEORDER FROM SALESTABLE T0  WHERE SALESID = ? ;");
define("EDITAR_ORDEN_VENTA_2", "SELECT ITEMID,NAME,SALESUNIT,SALESQTY,STF_SALESPRICE,T1.INVENTSITEID,T1.INVENTLOCATIONID,'0' AS CAMBIOWS , '0' AS PRECIOWS,T0.CURRENCYCODE FROM SALESLINE T0 INNER JOIN INVENTDIM T1 ON (T1.INVENTDIMID = T0.INVENTDIMID) WHERE SALESID = ? ;" );
define("INSERT_KARDEX","INSERT INTO ".INTERNA.".dbo.kardex (usuario,nombre,fecha,movimiento,sucursal) VALUES (?,?,getdate(),?,'".SUCURSAL."');");
define("ESTADISTICO_LOGIN", "select count(usuario)as cuenta,usuario,nombre from ".INTERNA.".dbo.kardex where movimiento='CTZN' group by usuario,nombre order by 1 desc;");
define("PRECIOS_LIMITE","SELECT T1.ACCOUNTNUM AS Clave, T1.CREDITMAX AS LimiteDeCredito, (SELECT sum(CustTrans.AMOUNTMST) FROM CustTrans WHERE CUSTTRANS.ACCOUNTNUM=T1.ACCOUNTNUM) AS Saldo, (SELECT CASE T1.CREDITMAX WHEN 0 THEN 100 ELSE ((SELECT sum(CustTrans.AMOUNTMST) FROM CustTrans WHERE CUSTTRANS.ACCOUNTNUM=T1.ACCOUNTNUM)*100/T1.CREDITMAX) END) as Porcentaje FROM  CustTable T1 WHERE T1.ACCOUNTNUM = ? ;");
define("EXISTENCIA_LOTE","SELECT T0.ITEMID 'Articulo', T1.INVENTLOCATIONID 'Almacen',  T1.INVENTBATCHID 'Lote', SUM(T0.AVAILPHYSICAL) 'Existencia' FROM INVENTSUM T0 INNER JOIN INVENTDIM T1 ON T0.INVENTDIMID=T1.INVENTDIMID WHERE T0.ITEMID = ? AND T1.INVENTSITEID!='CEDSCHI' AND T1.INVENTSITEID = ? GROUP BY T0.ITEMID, T1.INVENTSITEID, T1.INVENTLOCATIONID, T1.INVENTBATCHID HAVING SUM(T0.AVAILPHYSICAL)>0");
define("NEGADOS","SELECT COUNT(CODIGO_ARTICULO) AS conteoNegado  FROM NEGADOS T0 INNER JOIN USERINFO T1 ON (T1.NETWORKALIAS = T0.VENDEDOR) INNER JOIN CUSTTABLE T2 ON (T2.ACCOUNTNUM = T0.CLIENTE) INNER JOIN DIRPARTYTABLE T3 ON (T3.RECID = T2.PARTY) WHERE T0.VENDEDOR = ? AND  FECHA BETWEEN DATEADD(mm, DATEDIFF(mm,0,GETDATE()), 0) AND DATEADD(DAY,6,( DATEADD(DAY, 1-DATEPART(WEEKDAY, CURRENT_TIMESTAMP), CURRENT_TIMESTAMP)));");
define("CTZN_VS_VTAS", "dbo.ATP_ResumenCTZN_VS_VTAS_Sucursales;");
define("INSERT_LOG_WS_INAX","insert into ".INTERNA.".dbo.LogInax (USUARIO,FECHA,TIPO,IP,COMPANY,PARAMETROS,RESPONSE,ESTATUS) VALUES (?,getdate(),?,?,?,?,?,?);");
define("GET_FRACCIONADOS", "SELECT T0.ITEMID 'Articulo', T1.NAMEALIAS 'DescripcionArticulo', T0.AVAILPHYSICAL 'FisicaDisponible', T0.INVENTLOCATIONID 'Almacen', T0.DESCRIPTION 'Descripcion' FROM STF_ITEMWASTEAVAILABLE T0 INNER JOIN INVENTTABLE T1 ON T0.ITEMID=T1.ITEMID  WHERE T0.INVENTLOCATIONID = ? AND T0.ITEMID = ? ;");
define("GET_CREDITO", "SELECT T0.SALESID, T0.CUSTACCOUNT,T1.BLOCKED FROM SALESTABLE T0 INNER JOIN CUSTTABLE T1 ON (T0.CUSTACCOUNT = T1.ACCOUNTNUM) WHERE T0.SALESID = ? ;");
define("LAST_VENTAS","SELECT '<i class=\"material-icons\" style=\"color:green;cursor:pointer\" onclick=\"detalleClienteVenta('+char(39)+CINV.SALESID+char(39)+',$(this))\">add_circle</i>' '0',CINV.SALESID '1',CONVERT(VARCHAR(255),CUSTTR.TRANSDATE,103) '2',CUSTTR.ACCOUNTNUM '3',DIRP2.NAME '4',DIRP.NAME '5'	FROM CUSTTRANS CUSTTR INNER JOIN CUSTINVOICEJOUR CINV ON (CINV.INVOICEID = CUSTTR.INVOICE) INNER JOIN HCMWORKER HCMW ON (HCMW.RECID = CINV.WORKERSALESTAKER) INNER JOIN DIRPARTYTABLE DIRP ON (DIRP.RECID = HCMW.PERSON) INNER JOIN CUSTTABLE CUST ON (CUST.ACCOUNTNUM = CUSTTR.ACCOUNTNUM) INNER JOIN DIRPARTYTABLE DIRP2 ON (DIRP2.RECID = CUST.PARTY) WHERE CUSTTR.ACCOUNTNUM = ?  AND CUSTTR.INVOICE LIKE 'FV-%'  ORDER BY CUSTTR.TRANSDATE DESC;");
define("LAST_VENTAS2","SELECT '<i class=\"material-icons\" style=\"color:green;cursor:pointer\" onclick=\"detalleClienteVenta('+char(39)+CINV.SALESID+char(39)+',$(this))\">add_circle</i>' '0',CINV.SALESID '1',CONVERT(VARCHAR(255),CUSTTR.TRANSDATE,103) '2',CUSTTR.ACCOUNTNUM '3',DIRP2.NAME '4',DIRP.NAME '5'	FROM CUSTTRANS CUSTTR INNER JOIN CUSTINVOICEJOUR CINV ON (CINV.INVOICEID = CUSTTR.INVOICE) INNER JOIN HCMWORKER HCMW ON (HCMW.RECID = CINV.WORKERSALESTAKER) INNER JOIN DIRPARTYTABLE DIRP ON (DIRP.RECID = HCMW.PERSON) INNER JOIN CUSTTABLE CUST ON (CUST.ACCOUNTNUM = CUSTTR.ACCOUNTNUM) INNER JOIN DIRPARTYTABLE DIRP2 ON (DIRP2.RECID = CUST.PARTY) WHERE CUSTTR.ACCOUNTNUM = ?  AND CUSTTR.INVOICE LIKE 'FV-%'  ORDER BY CUSTTR.TRANSDATE DESC;");
define("GET_ARCHIVO_ADJUNTO_COT","SELECT (CONCAT(CONVERT(VARCHAR,CREATEDDATETIME,103),' ',CONVERT(VARCHAR,CREATEDDATETIME,108))) AS CREATEDDATETIME,TYPEID,NAME,RESTRICTION,NOTES,VALUERECID,REFTABLEID FROM DOCUREF WHERE NOTES IS NOT NULL AND RESTRICTION != '1' AND REFRECID = (SELECT RECID FROM SALESQUOTATIONTABLE WHERE QUOTATIONID = ? )");
define("GET_ARCHIVO_ADJUNTO_OV", "SELECT (CONCAT(CONVERT(VARCHAR,CREATEDDATETIME,103),' ',CONVERT(VARCHAR,CREATEDDATETIME,108))) AS CREATEDDATETIME,TYPEID ,NAME ,RESTRICTION ,NOTES ,VALUERECID ,REFTABLEID FROM DOCUREF  WHERE (NOTES IS NOT NULL or NAME IS NOT NULL) AND RESTRICTION != '1' AND REFRECID = (SELECT RECID FROM SALESTABLE WHERE SALESID = ? )");
define("GET_DATA_NEGADOS","SELECT T0.VENDEDOR AS '0',CODIGO_ARTICULO AS '1',NOMBRE AS '2',T3.NAME AS '3',SITIO AS '4',CANTIDAD_NEGADA AS '5',UOM AS '6',ISNULL(CONVERT(VARCHAR(255),COMENTARIO),'SIN COMENTARIOS') AS '7',CONVERT(VARCHAR,FECHA,103) AS '8' FROM NEGADOS T0 INNER JOIN USERINFO T1 ON (T1.NETWORKALIAS = T0.VENDEDOR) INNER JOIN CUSTTABLE T2 ON (T2.ACCOUNTNUM = T0.CLIENTE) INNER JOIN DIRPARTYTABLE T3 ON (T3.RECID = T2.PARTY) WHERE T0.VENDEDOR != 'sistemas07' AND FECHA BETWEEN DATEADD(mm, DATEDIFF(mm,0,GETDATE()), 0) AND DATEADD(DAY,6,( DATEADD(DAY, 1-DATEPART(WEEKDAY, CURRENT_TIMESTAMP), CURRENT_TIMESTAMP))) GROUP BY CODIGO_ARTICULO,VENDEDOR,NOMBRE,CLIENTE,SITIO,CANTIDAD_NEGADA,UOM,CONVERT(VARCHAR(255),COMENTARIO),FECHA,T1.NAME,T3.NAME  ORDER BY 1,9,5;");
define("GET_DATA_NEGADOS_FILTER","SELECT T0.VENDEDOR AS '0',CODIGO_ARTICULO AS '1',NOMBRE AS '2',T3.NAME AS '3',SITIO AS '4',CANTIDAD_NEGADA AS '5',UOM AS '6',ISNULL(CONVERT(VARCHAR(255),COMENTARIO),'SIN COMENTARIOS') AS '7',CONVERT(VARCHAR,FECHA,103) AS '8' FROM NEGADOS T0 INNER JOIN USERINFO T1 ON (T1.NETWORKALIAS = T0.VENDEDOR) INNER JOIN CUSTTABLE T2 ON (T2.ACCOUNTNUM = T0.CLIENTE) INNER JOIN DIRPARTYTABLE T3 ON (T3.RECID = T2.PARTY) WHERE T0.VENDEDOR != 'sistemas07' AND FECHA BETWEEN ? AND ? and T0.vendedor like ? GROUP BY CODIGO_ARTICULO,VENDEDOR,NOMBRE,CLIENTE,SITIO,CANTIDAD_NEGADA,UOM,CONVERT(VARCHAR(255),COMENTARIO),FECHA,T1.NAME,T3.NAME  ORDER BY 1,9,5;");
define("GET_REFRESH_LINES_COT","SELECT T1.ITEMID,T1.NAME,T1.SALESQTY,T1.SALESUNIT,T2.INVENTSITEID,T2.INVENTLOCATIONID ,T1.LINEAMOUNT AS MONTOCARGO,(T1.LINEAMOUNT*1.16) AS MONTOCARGOIVA, ISNULL(T1.STF_OBSERVATIONS,'') AS STF_OBSERVATIONS FROM SALESQUOTATIONTABLE T0 INNER JOIN SALESQUOTATIONLINE T1 ON (T1.QUOTATIONID = T0.QUOTATIONID) INNER JOIN INVENTDIM T2 ON (T2.INVENTDIMID = T1.INVENTDIMID) WHERE T0.QUOTATIONID = ? ;");
define("GET_REFRESH_LINES_OV", "SELECT T1.ITEMID,T1.NAME,T1.SALESQTY,T1.SALESUNIT,T2.INVENTSITEID,T2.INVENTLOCATIONID ,T1.LINEAMOUNT AS MONTOCARGO,(T1.LINEAMOUNT*1.16) AS MONTOCARGOIVA, ISNULL(T1.STF_OBSERVATIONS,'') AS STF_OBSERVATIONS FROM SALESTABLE T0 INNER JOIN SALESLINE T1 ON (T1.SALESID = T0.SALESID) INNER JOIN INVENTDIM T2 ON (T2.INVENTDIMID = T1.INVENTDIMID) WHERE T0.SALESID = ? ;");
define("GET_STATUS_ALERTA","SELECT * FROM STF_CREDITAPPROVALLIST WHERE SALESID = ? ;");
define("GET_STATUS_BLOQUEO","SELECT T0.SALESID, T0.CUSTACCOUNT,T1.BLOCKED FROM SALESTABLE T0 INNER JOIN CUSTTABLE T1 ON (T0.CUSTACCOUNT = T1.ACCOUNTNUM) WHERE T0.SALESID = ? ;");
define("KARDEX_VENTAS_COT","INSERT INTO KARDEXVENTAS (OVID,CPAGO,LINXML,CABXML,MPAGO,ORIGENVENTA,TIPO,FECHA,DOCORIGINAL,USUARIO) VALUES(?,?,?,?,?,?,0,GETDATE(),'0',?);");
define("KARDEX_VENTAS_OV","INSERT INTO KARDEXVENTAS (OVID,CPAGO,LINXML,CABXML,MPAGO,ORIGENVENTA,TIPO,FECHA,DOCORIGINAL,USUARIO) VALUES(?,?,?,?,?,?,1,GETDATE(),'0',?);");
define("TARJETA_PAGO_COTIZACION", "select top 1 CPAGO from dbo.KARDEXVENTAS where OVID = ? order by fecha desc ;");
define("GET_INVOICE_DELIVERY_ADDRESS","SELECT T5.RECID,T6.NAME FROM CUSTTABLE T0 INNER JOIN DIRPARTYTABLE T1 ON T0.PARTY=T1.RECID INNER JOIN DIRPARTYLOCATION T2 ON T2.PARTY=T1.RECID INNER JOIN LOGISTICSLOCATION T3 ON T2.LOCATION=T3.RECID INNER JOIN DIRPARTYLOCATIONROLE T4 ON T4.PARTYLOCATION=T2.RECID INNER JOIN LOGISTICSPOSTALADDRESS T5 ON T5.LOCATION=T3.RECID AND T5.VALIDTO >= GETDATE() INNER JOIN LOGISTICSLOCATIONROLE T6 ON T4.LOCATIONROLE=T6.RECID WHERE T0.ACCOUNTNUM = ? AND (T6.NAME = 'Delivery' OR T6.NAME = 'Invoice');");
define("CONFIRMADOS_VS_CREADOS","select (select count(nombre) from ".INTERNA.".dbo.kardex where movimiento='CTZN')  as CTZN,(select count(nombre) from ".INTERNA.".dbo.kardex where movimiento='ORDVTA' )  as ORDVTA,(select count(nombre) from ".INTERNA.".dbo.kardex where movimiento='CTZNC' )  as CTZNC,(select count(nombre) from ".INTERNA.".dbo.kardex where movimiento='ORDVTAC')  as ORDVTC");
define("CONFIRMADOS_VS_CREADOS_POR_USUSRIO","select top 3 NOMBRE,USUARIO,
	(SELECT COUNT(nombre) FROM ".INTERNA.".dbo.kardex X WHERE movimiento='CTZN' AND X.nombre = T0.nombre)  AS CTZN,
	(SELECT COUNT(nombre) FROM ".INTERNA.".dbo.kardex X WHERE movimiento='ORDVTA' AND X.nombre = T0.nombre)  AS ORDVTA,
	(SELECT COUNT(nombre) FROM ".INTERNA.".dbo.kardex X WHERE movimiento='CTZNC' AND X.nombre = T0.nombre)  AS CTZNC,
	(SELECT COUNT(nombre) FROM ".INTERNA.".dbo.kardex X WHERE movimiento='ORDVTAC' AND X.nombre = T0.nombre)  AS ORDVTC FROM ".INTERNA.".dbo.kardex T0 GROUP BY T0.nombre,T0.USUARIO order by CTZN desc;");
define("GRAFICA_SUCURSAL","select t2.nombre,COUNT(sucursal) as conteo from ".INTERNA.".dbo.kardex t1 right join ".INTERNA.".dbo.sucursal t2 on t1.sucursal=t2.idsuc and fecha BETWEEN ? AND ? group by sucursal, t2.nombre order by conteo desc;");
define("SEMAFORO","select * from ".INTERNA.".dbo.semaforo;");
define("SEMAFORO_UPDATE","update ".INTERNA.".dbo.semaforo set sel='selected' where id= ?;");
define("SEMAFORO_RESET", "update ".INTERNA.".dbo.semaforo set sel='';");
define("SEMAFORO_ACTUAL","select * from ".INTERNA.".dbo.semaforo where sel='selected';");
define("LAST_ERROR","SELECT * FROM DBO.SYSEXCEPTIONTABLE WHERE CREATEDDATETIME between DATEADD(SECOND,-2,GETUTCDATE()) and GETUTCDATE() ORDER BY CREATEDDATETIME DESC");
/* querys para cotizacion */
define("GET_CARGOS_COT","select T0.QUOTATIONID,T1.VALUE from SALESQUOTATIONTABLE t0 inner join markuptrans t1 ON (t1.TRANSRECID = T0.RECID and t1.TRANSTABLEID=1967) where t0.QUOTATIONID=?");
define("GET_COTIZACION_CABEZERA","SELECT T0.workersalestaker as 'vendedor', CONVERT(VARCHAR(10), CONVERT(DATE, T0.receiptdaterequested, 106), 103) 'Fecha', CONVERT(VARCHAR(10), CONVERT(DATE, T0.quotationexpirydate, 106), 103) 'FechaVencimiento', T0.payment 'Pago',T0.QUOTATIONNAME 'NombreEntrega' from salesquotationtable T0  where T0.quotationid = ?;");
define("GET_VENDEDOR","SELECT TDIRP.NAME FROM  dirpartytable TDIRP INNER JOIN hcmworker HCMW  ON ( TDIRP.recid = HCMW.person )  WHERE  HCMW.recid = ?");
define("GET_ITEMS_COT","select INVENTDIMID 'almacen', ITEMID 'CodigoArticulo',NAME 'DescripcionArticulo',SALESQTY 'Cantidad',CURRENCYCODE 'Moneda',SALESUNIT 'Unidad',STF_SALESPRICE 'PrecioUnitario',LINEAMOUNT 'Importe',stf_observations 'ComentarioLinea' from SALESQUOTATIONLINE where quotationid = ? order by stf_observations ASC;");
define("GET_ALMACEN_COTIZACION","select INVENTSITEID 'Sitio',INVENTLOCATIONID 'Almacen' from inventdim where INVENTDIMID=?;");
define("GET_OV_REV","select top 1 PACKINGSLIPID from CUSTPACKINGSLIPJOUR where SALESID= ?;");
define("DEV_EXISTENCIAS","EXECUTE devGetExistencias ?,?,?,?;");
define("GET_ITEM_TYPE","SELECT ITEMTYPE FROM INVENTTABLE WHERE ITEMID = ? AND DATAAREAID = '".COMPANY."' ");
define("GET_ITEM_CONTEO","SELECT COUNT(ITEMID) as CONTEO FROM INVENTSUM INNER JOIN INVENTDIM  ON INVENTDIM.INVENTDIMID=INVENTSUM.INVENTDIMID AND INVENTDIM.DATAAREAID = '".COMPANY."'
				  WHERE ITEMID = ?
				  AND INVENTSUM.DATAAREAID = '".COMPANY."'
				  AND INVENTDIM.INVENTSITEID!='CEDSCHI' 
				  AND INVENTDIM.INVENTSITEID = ?
				  AND INVENTDIM.INVENTLOCATIONID = ? ;");
define("GET_ITEM_EXISTENCIA",
        "SELECT SUM(Existencia) 'Existencia'
	FROM (
		SELECT
			T0.AVAILPHYSICAL 'Existencia'
		FROM INVENTSUM T0
			INNER JOIN INVENTDIM T1 ON T0.INVENTDIMID=T1.INVENTDIMID AND T1.DATAAREAID = '".COMPANY."'
		WHERE T0.ITEMID = ?
			AND T1.INVENTSITEID!='CEDSCHI' 
			AND T1.INVENTSITEID = ?
			AND T1.INVENTLOCATIONID = ?
			AND T1.WMSLOCATIONID = ?
			AND T0.DATAAREAID='".COMPANY."'	)x"); 
/*querys de index*/
define("MONTO_ETIQUETA","SELECT DISTINCT T0.ITEMID, SUM(T2.LINEAMOUNT) AS MONTO
	FROM INVENTTRANSORIGIN T0
	INNER JOIN SALESLINE T2 ON (T2.SALESID = T0.REFERENCEID AND T2.ITEMID = T0.ITEMID)
	INNER JOIN ECORESPRODUCT T3 ON (T3.DISPLAYPRODUCTNUMBER = T0.ITEMID)
	LEFT JOIN ECORESPRODUCTCATEGORY T4 ON (T4.PRODUCT = T3.RECID AND T4.CATEGORYHIERARCHY ='5637146828')
	LEFT JOIN ECORESCATEGORY T5 ON (T5.RECID = T4.CATEGORY)
	WHERE T2.SALESID = ?
	AND ISNULL(T5.NAME,'SIN CATEGORIA') != 'SERVICIOS'
	AND	T0.DATAAREAID = '".COMPANY."'
	AND	T2.DATAAREAID = '".COMPANY."'
	GROUP BY T0.ITEMID");
define("DATOS_PAGO_OV","select t0.PAYMMODE,t0.PAYMENT from SALESTABLE t0 where t0.SALESID=?");
define("TODAS_OV","SELECT T0.SALESID, T0.CREATEDDATETIME, T0.CUSTACCOUNT,T0.SALESNAME, T0.INVENTSITEID, T0.INVENTLOCATIONID, T0.DLVMODE, T3.NAME AS VENDEDOR, T0.SALESSTATUS, T1.PROCESO AS PROCESO, T1.PACKINGSLIPID AS CUST_PACKINGSLIPID
                    FROM dbo.SALESTABLE AS T0 LEFT OUTER JOIN
                        dbo.VIEW_STF_DELIVERY() AS T1 ON T1.SALESID = T0.SALESID LEFT OUTER JOIN
                        dbo.HCMWORKER AS T2 ON T2.RECID = T0.WORKERSALESTAKER LEFT OUTER JOIN
                        dbo.DIRPARTYTABLE AS T3 ON T3.RECID = T2.PERSON LEFT OUTER JOIN
                        dbo.view_PackingSlipJour AS T4 ON T4.SALESID = T0.SALESID
                    WHERE (T0.CREATEDDATETIME > DATEADD(MONTH, - 1, GETDATE())) and DATAAREAID= '".COMPANY."' order by T0.SALESID desc OFFSET 0 ROWS FETCH NEXT (SELECT 10) ROWS ONLY;" );
define("DATOS_ETIQUETA","SELECT SALES.SALESID,SALES.CUSTACCOUNT,DBO.getClienteNombre(SALES.CUSTACCOUNT) AS 'NOMBRECLIENTE',DBO.vendedorName(DBO.getRecidDynamicUser( ? )) AS 'NOMBREVENDEDOR',CUST.RFC_MX AS RFC,LOGEL.LOCATOR AS TELEFONO,LOGEL.LOCATOREXTENSION AS EXTENSION FROM SALESTABLE SALES INNER JOIN CUSTTABLE CUST ON (CUST.ACCOUNTNUM = SALES.CUSTACCOUNT) LEFT JOIN DIRPARTYTABLE DIRP ON (DIRP.RECID = CUST.PARTY) LEFT JOIN LOGISTICSELECTRONICADDRESS LOGEL ON (LOGEL.RECID = DIRP.PRIMARYCONTACTPHONE) WHERE SALES.SALESID = ? ;");

define("GET_ALTERNATIVOS_1","SELECT T4.ITEMID,Sum (T4.AVAILPHYSICAL) EXISTENCIA,T3.INVENTSITEID into ##existenciaart FROM inventsum T4 INNER JOIN inventdim T3 ON T3.INVENTDIMID=T4.INVENTDIMID and T3.DATAAREAID=T4.DATAAREAID WHERE T4.AVAILPHYSICAL > 0 and t3.DATAAREAID='".COMPANY."' GROUP BY T3.INVENTSITEID,T4.ITEMID; ");
define("GET_ALTERNATIVOS_2","SELECT T2.DISPLAYPRODUCTNUMBER AS ITEMID,T2.SEARCHNAME AS DESCRIPCION,ISNULL(T3.EXISTENCIA,0) AS EXISTENCIA FROM EcoResProductRelationTable T0 INNER JOIN ECORESPRODUCT T1 on T1.RECID=t0.PRODUCT1 INNER JOIN ECORESPRODUCT T2 ON (T2.RECID = T0.PRODUCT2) LEFT JOIN ##existenciaart T3 ON (T3.ITEMID = T2.DISPLAYPRODUCTNUMBER AND T3.INVENTSITEID = :sitio ) WHERE T1.DISPLAYPRODUCTNUMBER = :item ");
define("GET_ALTERNATIVOS_3","drop table ##existenciaart;");

define("FACTURA_ERROR","
    SELECT C.INVOICEID AS 'FACTURA', C.SALESID 'OV',C.INVOICEDATE AS 'FECHA', C.INVENTSITEID AS 'SITIO'
	, C.INVOICEACCOUNT AS 'CLIENTE', C.CURRENCYCODE AS 'MONEDA'
	, C.INVOICEAMOUNT AS 'MONTO', C.CREATEDBY AS 'CREADO'
	, E.CFDIRESPONSE AS 'RESPUESTA', E.STF_CFDIRESPONSE AS 'STF_RESPUESTA'
	, CUST.RFC_MX AS 'RFC',
	E.CFDIUUID as 'UUID'
	FROM CUSTINVOICEJOUR C
	INNER JOIN EINVOICEJOUR_MX E ON (C.RECID = E.REFRECID)
	INNER JOIN CUSTTABLE CUST ON (CUST.ACCOUNTNUM = C.INVOICEACCOUNT)
	WHERE C.SALESID != ''
	AND E.CFDISTATUS in(2,3) " 
    );
define("FACTURA_ERROR_FILTRO_FECHA","
    SELECT C.INVOICEID AS 'FACTURA'
                           , C.SALESID AS 'OV'
                           , C.INVOICEDATE AS 'FECHA'
                           , C.INVENTSITEID AS 'SITIO'
                           , C.INVOICEACCOUNT AS 'CLIENTE'
                           , C.CURRENCYCODE AS 'MONEDA'
                           , C.INVOICEAMOUNT AS 'MONTO'
                           , C.CREATEDBY AS 'CREADO'
                           , E.CFDIRESPONSE AS 'RESPUESTA'
                           , SUBSTRING(E.STF_CFDIRESPONSE,(CHARINDEX('MensajeParaCliente&gt',E.STF_CFDIRESPONSE)+22),iif((CHARINDEX('/MensajeParaCliente&gt',E.STF_CFDIRESPONSE)-4)=-4,1000,(CHARINDEX('/MensajeParaCliente&gt',E.STF_CFDIRESPONSE)-4))-(CHARINDEX('MensajeParaCliente&gt',E.STF_CFDIRESPONSE)+22)) AS 'STF_RESPUESTA'
                           , IIF( E.CFDIUUID = '','Sin UUID por estatus rechazado',E.CFDIUUID) AS 'UUID'
                           , CUST.RFC_MX AS 'RFC'
FROM CUSTINVOICEJOUR C
INNER JOIN EINVOICEJOUR_MX E ON (C.RECID = E.REFRECID)
INNER JOIN CUSTTABLE CUST ON (CUST.ACCOUNTNUM = C.INVOICEACCOUNT)
WHERE C.INVOICEDATE BETWEEN ? AND  ? 
	AND C.SALESID != ''
	AND E.CFDISTATUS in(2,3) ");
define("TODAS_COTIZACIONES",  
        "SELECT        T0.QUOTATIONID,
					T0.CREATEDDATETIME,
					T0.CUSTACCOUNT,
					T0.QUOTATIONNAME,
					T0.INVENTSITEID,
					T0.INVENTLOCATIONID,
					T0.DLVMODE,
					T3.NAME AS VENDEDOR, 
                    T0.QUOTATIONSTATUS,
					T0.SALESIDREF

	FROM            dbo.SALESQUOTATIONTABLE AS T0 INNER JOIN
					dbo.HCMWORKER AS T2 ON T2.RECID = T0.WORKERSALESTAKER INNER JOIN
					dbo.DIRPARTYTABLE AS T3 ON T3.RECID = T2.PERSON
	WHERE			(T0.CREATEDDATETIME > DATEADD(MONTH, - ".PERIODO_DE_VENTA.", GETDATE())) AND (T0.DATAAREAID = '".COMPANY."') ");
define("TODAS_COTIZACIONES_USER",
        "SELECT  T0.QUOTATIONID 
	,T0.QUOTATIONID
	,T0.CREATEDDATETIME
	,T0.CUSTACCOUNT
	,T0.QUOTATIONNAME
	,T0.INVENTSITEID
	,T0.INVENTLOCATIONID
	,T0.DLVMODE,
	T0.QUOTATIONSTATUS
	,T0.SALESIDREF
	FROM SALESQUOTATIONTABLE T0
	WHERE T0.CREATEDDATETIME > DATEADD(MONTH, - ".PERIODO_DE_VENTA.",GETDATE())
	AND T0.DATAAREAID = '".COMPANY."'
	AND T0.WORKERSALESTAKER = ?"
);
define("TODAS_OV_PERIODO","SELECT top 2000 T0.salesid,T0.custaccount,T0.salesname,T0.dlvmode,T0.inventsiteid
				,T0.inventlocationid
			,(SELECT TDIRP.NAME FROM   dirpartytable TDIRP INNER JOIN hcmworker HCMW ON ( TDIRP.recid = HCMW.person ) WHERE  HCMW.recid = T0.workersalestaker) AS 'VENDEDOR'
			,T0.CREATEDDATETIME
            ,t0.SALESSTATUS
            ,(select top 1 T4.PACKINGSLIPID from  ##tbl1 T4 where T4.SALESID=T0.SALESID)  AS PACKINGSLIPIDJOUR
FROM		SALESTABLE T0
			LEFT JOIN HCMWORKER T2 ON (T2.RECID = T0.WORKERSALESTAKER)
			LEFT JOIN DIRPARTYTABLE T3 ON (T3.RECID = T2.PERSON)
	WHERE		(T0.CREATEDDATETIME > DATEADD(MONTH, - 1, GETDATE()))
	AND T0.DATAAREAID = '".COMPANY."' order by T0.CREATEDDATETIME desc");
define("TODAS_OV_PERIODO_USUARIO_1","select * into ##tbl1 from view_PackingSlipJour");
define("TODAS_OV_PERIODO_USUARIO_3", "drop table ##tbl1");
define("TODAS_OV_PERIODO_USUARIO", "SELECT T0.salesid,T0.custaccount,T0.salesname,T0.dlvmode,T0.inventsiteid
				,T0.inventlocationid
			,T0.CREATEDDATETIME
            ,t0.SALESSTATUS
			,(select top 1 T4.PACKINGSLIPID from ##tbl1 T4 where T4.SALESID=T0.SALESID)  AS PACKINGSLIPIDJOUR
FROM		SALESTABLE T0
			LEFT JOIN HCMWORKER T2 ON (T2.RECID = T0.WORKERSALESTAKER)
			LEFT JOIN DIRPARTYTABLE T3 ON (T3.RECID = T2.PERSON)
	WHERE		(T0.CREATEDDATETIME > DATEADD(MONTH, - 1, GETDATE()))
	AND T0.DATAAREAID = '".COMPANY."' and T0.WORKERSALESTAKER=? ");
/** QUERYS DE MERMA*/
/**
 * Este query es el costo promedio recibe un item y un sitio
 */
define("COSTO_PROMEDIO","select (SUM(T0.POSTEDVALUE)-(CAST(SUM(T0.PHYSICALVALUE) AS DECIMAL(10,2))*-1)) /  (SUM(T0.PostedQty) + SUM(T0.Received - T0.Deducted)) + SUM(T0.Registered - T0.Picked) as 'COSTO'
from INVENTSUM T0 left join INVENTDIM T1 on T0.INVENTDIMID = T1.INVENTDIMID 
where
T0.itemId = ?
and T1.INVENTSITEID = ?
and T1.DATAAREAID='".COMPANY."'
and T0.DATAAREAID='".COMPANY."';");

define("GET_ALMACENES_MERMA","select INVENTLOCATIONID,NAME from INVENTLOCATION where INVENTLOCATIONID LIKE '%MRMA%';");

/** queries de errores inax*/

define("TOTAL_PETICIONES_WS","select COUNT(ID) as total from ".INTERNA.".dbo.loginax where fecha between ? and ? ;");
define("TOTAL_PETICIONES_WS_ERROR","select COUNT(ID) as total from ".INTERNA.".dbo.loginax where  estatus=2 and fecha between ? and ?;");
define("TOTAL_PETICIONES_WS_OK","select COUNT(ID) as total from ".INTERNA.".dbo.loginax where estatus=1 and fecha between ? and ?;");
define("TOTAL_PETICIONES_WS_PRECIO","select COUNT(ID) as total from ".INTERNA.".dbo.loginax where estatus=2 and tipo= 'precios' and fecha between ? and ?;");
define("TOTAL_PETICIONES_WS_LIMITE","select COUNT(ID) as total from ".INTERNA.".dbo.loginax where estatus=2 and tipo= 'Limite de credito' and fecha between ? and ?;");
define("TOTAL_PETICIONES_WS_COT_OV","select COUNT(ID) as total from ".INTERNA.".dbo.loginax where estatus=2 and tipo= 'convertir COT a OV' and fecha between ? and ?;");
define("TOTAL_PETICIONES_WS_LINEAS","select COUNT(ID) as total from ".INTERNA.".dbo.loginax where estatus=2 and (tipo= 'lineas' or tipo= 'encabezado') and fecha between ? and ?;");
define("TOTAL_PETICIONES_WS_REMISION","select COUNT(ID) as total from ".INTERNA.".dbo.loginax where estatus=2 and tipo= 'Remision' and fecha between ? and ?;");
define("TOTAL_PETICIONES_WS_CLIENTE_NEW_ERROR","select COUNT(ID) as total from ".INTERNA.".dbo.loginax where estatus=2 and tipo= 'ALTACLIENTE' and fecha between ? and ?;");
define("TOTAL_PETICIONES_WS_IMPRESION_PDF_ERROR","select COUNT(ID) as total from ".INTERNA.".dbo.loginax where estatus=2 and (tipo= 'Impresion de remision' or tipo='Impresion cotizacion') and fecha between ? and ?;");
define("TOTAL_PETICIONES_WS_FACTURA", "select count(ID) as 'total' from ".INTERNA.".dbo.loginax where TIPO='factura' and ESTATUS=1 and fecha between ? and ?;");
define("TOTAL_PETICIONES_WS_FACTURA_ERROR", "select count(ID) as 'total' from ".INTERNA.".dbo.loginax where TIPO='factura' and ESTATUS=2 and fecha between ? and ?;");
define("TOTAL_PETICIONES_WS_PRECIO_COMPLETE","select COUNT(ID) as total from ".INTERNA.".dbo.loginax where estatus=1 and (tipo= 'precios' or tipo='PrecioBloqueado') and fecha between ? and ?;");
//define("TOTAL_PETICIONES_WS_IMPRESIONES_COMPLETE","select COUNT(ID) as total from ".INTERNA.".dbo.loginax where estatus=1 and (tipo= 'Limite de credito' or tipo='PrecioBloqueado') and fecha between ? and ?;");
define("TOTAL_PETICIONES_WS_COT_OV_COMPLETE","select COUNT(ID) as total from ".INTERNA.".dbo.loginax where estatus=1 and tipo= 'convertir COT a OV' and fecha between ? and ?;");
define("TOTAL_PETICIONES_WS_LINEAS_COMPLETE","select COUNT(ID) as total from ".INTERNA.".dbo.loginax where estatus=1 and (tipo= 'lineas' or tipo= 'encabezado') and fecha between ? and ?;");
define("TOTAL_PETICIONES_WS_REMISION_COMPLETE","select COUNT(ID) as total from ".INTERNA.".dbo.loginax where estatus=1 and (tipo= 'Remision' or tipo='Limite de credito') and fecha between ? and ?;");
define("TOTAL_PETICIONES_WS_CLIENTE_NEW","select COUNT(ID) as total from ".INTERNA.".dbo.loginax where estatus=1 and tipo= 'ALTACLIENTE' and fecha between ? and ?;");
define("TOTAL_PETICIONES_WS_IMPRESION_PDF","select COUNT(ID) as total from ".INTERNA.".dbo.loginax where estatus=1 and (tipo= 'Impresion de remision' or tipo='Impresion cotizacion') and fecha between ? and ?;");
define("TOTAL_PETICIONES_TBL","select top 150 ID,USUARIO,FECHA,TIPO,IP,ESTATUS from ".INTERNA.".dbo.loginax where estatus=2 and fecha between ? and ?  order by fecha desc;");
define("ERRORES_USUARIO","SELECT USUARIO,COUNT(USUARIO) as C FROM ".INTERNA.".dbo.loginax where estatus=2 and fecha between ? and ? group by USUARIO order by C DESC;"); 
/* querys de comisionistas*/
define("COMISIONISTA_LISTAR","select * from ".INTERNA.".dbo.comComisionista;");
$_SESSION['MESES_STR']=array(1=>"Enero",2=>"Febrero",3=>"Marzo",4=>"Abril",5=>"Mayo",6=>"Junio",7=>"Julio",8=>"Agosto",9=>"Septimbre",10=>"Octubre",11=>"Noviembre",12=>"Diciembre");
define("NEW_COMISIONISTA","insert into ".INTERNA.".dbo.comComisionista (nombre,direccion,telefono,estado,ciudad) values(?,?,?,?,?);");
define("COMISIONISTA_CLIENTE_LISTAR","select idcomComisionCliente,mes,item,nombre as comisionista,comision,T3.NAME as clientenom,cliente from ".INTERNA.".dbo.comComisionCliente T0 inner join ".INTERNA.".dbo.comComisionista T1 on T0.idComisionista= T1.idComisionista inner join CUSTTABLE T2 on T2.ACCOUNTNUM = T0.cliente INNER JOIN DIRPARTYTABLE T3 ON T2.PARTY=T3.RECID;");
define("NEW_COMISIONISTA_CLIENTE","insert into ".INTERNA.".dbo.comComisionCliente (mes,item,idComisionista,cliente,comision) values(?,?,?,?,?);");
define("DELETE_COMISIONISTA_CLIENTE","delete from ".INTERNA.".dbo.comComisionCliente where idcomComisionCliente= ?; ");
define("GET_COMISIONISTA_DATA","SELECT * FROM ".INTERNA.".dbo.comComisionista where idComisionista= :id ");
define("COMISIONISTA_CLIENTE_REPORTE1","select  * INTO   ##T1 from ".INTERNA.".dbo.comComisionCliente ;");
define("COMISIONISTA_CLIENTE_REPORTE2","select  * INTO   ##T2 from ".INTERNA.".dbo.comComisionista ;");
define("COMISIONISTA_CLIENTE_REPORTE3","DROP TABLE ##T1,##T2;");
define("COMISIONISTA_CLIENTE_REPORTE","select SUM(T0.LINEAMOUNT) as TOTAL,T2.idComisionista, T1.ITEM, T2.NOMBRE,T1.COMISION,T3.SALESNAME,SUM(T0.LINEAMOUNT) * T1.COMISION AS TOTALPAGO FROM SALESLINE T0
    INNER JOIN ##T1 T1 ON T0.ITEMID=T1.ITEM AND T0.CUSTACCOUNT= T1.CLIENTE AND T1.MES= :mes1
    INNER JOIN ##T2 T2 ON T1.IDCOMISIONISTA=T2.IDCOMISIONISTA
    INNER JOIN SALESTABLE T3 ON T3.SALESID = T0.SALESID
    WHERE T0.SALESSTATUS=3 and MONTH(T0.SHIPPINGDATEREQUESTED) = :mes
    AND YEAR(T0.SHIPPINGDATEREQUESTED) =YEAR(GETDATE()) 
    AND T2.NOMBRE like :comisionista
    AND T3.SALESTYPE=3 AND T3.DATAAREAID='".COMPANY."' GROUP BY  T2.NOMBRE,T1.COMISION,T3.CUSTACCOUNT,T3.SALESNAME,T1.ITEM,T2.idComisionista");
define("GET_INVOICE_DIREC","SELECT T5.ADDRESS,T5.RECID,(CASE T6.NAME WHEN 'Business' THEN 'Negocio' WHEN 'Delivery' THEN 'Entrega' WHEN 'Fixed asset' THEN 'Activo Fijo' WHEN 'Home' THEN 'Particular' WHEN 'Other' THEN 'Otros'  WHEN 'Invoice' THEN 'Facturacion' WHEN 'Payment' THEN 'Pago' WHEN 'Remit to' THEN 'Remitir a' WHEN 'Service' THEN 'Servicio' WHEN 'Third party shipping' THEN 'Direccion de envio a terceros' ELSE T6.NAME END) AS 'PROPOSITO'
FROM CUSTTABLE T0 INNER JOIN DIRPARTYTABLE T1 ON T0.PARTY=T1.RECID INNER JOIN DIRPARTYLOCATION T2 ON T2.PARTY=T1.RECID INNER JOIN LOGISTICSLOCATION T3 ON T2.LOCATION=T3.RECID INNER JOIN DIRPARTYLOCATIONROLE T4 ON T4.PARTYLOCATION=T2.RECID INNER JOIN LOGISTICSPOSTALADDRESS T5 ON T5.LOCATION=T3.RECID AND T5.VALIDTO >= GETDATE() 
INNER JOIN LOGISTICSLOCATIONROLE T6 ON T4.LOCATIONROLE=T6.RECID LEFT JOIN LOGISTICSADDRESSCOUNTY T7 ON T7.COUNTYID = T5.COUNTY LEFT JOIN LOGISTICSADDRESSSTATE T8 ON T8.STATEID = T5.STATE LEFT JOIN LOGISTICSADDRESSCOUNTRYREGION T9 ON T9.COUNTRYREGIONID = T8.COUNTRYREGIONID LEFT JOIN LOGISTICSADDRESSCOUNTRYREGIONTRANSLATION T10 ON T10.COUNTRYREGIONID = T9.COUNTRYREGIONID AND T10.LANGUAGEID = 'es' 
WHERE T0.ACCOUNTNUM = ? and T6.NAME='Invoice' GROUP BY T0.ACCOUNTNUM,T5.ADDRESS,T5.RECID,T3.DESCRIPTION,T2.ISPRIMARY,T0.PARTY,T6.NAME ,T7.NAME,T5.STREET,T5.STATE,T5.CITY,T5.ZIPCODE,T8.NAME,T10.SHORTNAME ORDER BY T2.ISPRIMARY DESC;");
define("GET_INVOICE_LINES","select LINENUM,SALESPRICE,LINEPERCENT,TAXGROUP from SALESLINE where SALESID = ?");
define("USER_PERMISSIONS","select t1.idRoll from ".INTERNA.".dbo.usrRollAssigned t1 inner join ".INTERNA.".dbo.usrUsr t2 on t1.idUsr=t2.idUsr where usuario = ? ;");
define("PERMISO_LISTAR","select * from ".INTERNA.".dbo.usrRoll;");
define("USER_LIST","select * from ".INTERNA.".dbo.usrUsr order by Usuario;");
define("USER_LIST_ASIGNED","select t1.id,t2.Usuario,t3.Roll from ".INTERNA.".dbo.usrRollAssigned t1 inner join ".INTERNA.".dbo.usrUsr t2 on t1.idUsr=t2.idUsr inner join ".INTERNA.".dbo.usrRoll t3 on t3.idRoll=t1.idRoll" );
define("USER_BY_NETWORK_ALIAS","select ID from USERINFO where NETWORKALIAS=?");
define("LISTA_TRASPASOS","select T0.folio,T0.fecha,T0.cliente,T0.solicita,T0.articulo,T0.estatus,T0.cantidad,T0.almacen,T1.modificacion from ".INTERNA.".dbo.traspasosInax T0 inner join ".INTERNA.".dbo.traspasosinaxDetalle T1 on T0.folio=T1.folio");
define("LISTA_TRASPASOS_CEDIS","select T0.folio,T0.fecha,T0.cliente,T0.solicita,T0.articulo,T0.estatus,T0.cantidad,T0.almacen,T1.modificacion from ".INTERNA.".dbo.traspasosInax T0 inner join ".INTERNA.".dbo.traspasosinaxDetalle T1 on T0.folio=T1.folio where  T0.estatus in (4,1,2,3,5)");
define("LISTA_TRASPASOS_ALMACEN","select T0.folio,T0.fecha,T0.cliente,T0.solicita,T0.articulo,T0.estatus,T0.cantidad,T0.almacen,T1.modificacion from ".INTERNA.".dbo.traspasosInax T0 inner join ".INTERNA.".dbo.traspasosinaxDetalle T1 on T0.folio=T1.folio where  T0.estatus in (4,3,5);");
define("LISTA_TRASPASOS_ID","select T0.folio,T0.fecha,T0.cliente,T0.solicita,T0.articulo,T0.estatus,T0.cantidad,T0.almacen,T1.modificacion from ".INTERNA.".dbo.traspasosInax T0 inner join ".INTERNA.".dbo.traspasosinaxDetalle T1 on T0.folio=T1.folio where T0.folio = :id ");
define("LISTA_TRASPASO_DETALLE_CUERPO","select *  from ".INTERNA.".dbo.traspasosinaxDetalle where folio= :id ");
define("LISTA_TRASPASOS_ST","select * from ".INTERNA.".dbo.traspasosinax  ");
define("INSERT_TRASPASO",'Insert into '.INTERNA.'.dbo.traspasosInax (fecha,cliente,solicita,articulo,estatus,cantidad,almacen) values(GETDATE(),:cliente,:user,:item,1,:cant,:almacen);');
define("INSERT_TRASPASO_DETALLE","Insert into ".INTERNA.".dbo.traspasosinaxDetalle (folio,cantidad,articulo,vendedor,modificacion,usuario,motivo,comentarios) values ( :folio , :cantidad , :articulo , :vendedor ,GETDATE(), :usuario , :motivo , :comenta );");
define("UPDATE_TRASPASO_ESTATUS","UPDATE ".INTERNA.".dbo.traspasosInax SET estatus=:st WHERE folio= :folio;");
define("UPDATE_TRASPASO_DETALLE","UPDATE ".INTERNA.".dbo.traspasosInaxdetalle SET comentarioscedis= :comentarios , usuario= :user , modificacion=GETDATE() where folio= :id ");
define("CONSULTA_VENTAS_MES","SELECT T0.salesid,T0.salesname,T0.dlvmode
            ,(SELECT TDIRP.NAME FROM   dirpartytable TDIRP INNER JOIN hcmworker HCMW ON ( TDIRP.recid = HCMW.person ) WHERE  HCMW.recid = T0.workersalestaker) AS 'Vendedor'
            ,ISNULL((select proceso from VIEW_STF_DELIVERY('".COMPANY."') T1 where T1.SALESID = T0.SALESID),'SIN PROCESAR') AS PROCESO
            ,T0.CREATEDDATETIME
            ,ISNULL((SELECT NOTES  FROM DOCUREF  WHERE (NOTES IS NOT NULL or NAME IS NOT NULL) AND RESTRICTION != '1' AND REFRECID = (SELECT RECID FROM SALESTABLE T4 WHERE T4.SALESID =  T0.SALESID )),'N/D') as guia
            ,t0.SALESSTATUS
FROM    SALESTABLE T0
            LEFT JOIN HCMWORKER T2 ON (T2.RECID = T0.WORKERSALESTAKER)
            LEFT JOIN DIRPARTYTABLE T3 ON (T3.RECID = T2.PERSON)
WHERE		T0.DATAAREAID = '".COMPANY."' AND T0.DLVMODE='PAQUETERIA' AND T0.CREATEDDATETIME > :fecha and t0.CUSTACCOUNT like :cliente " );
define("DETALLE_OV","select sl.LINENUM,sl.ITEMID,sl.NAME,sl.SALESQTY,sl.SALESUNIT from SalesLine sl where sl.SALESID= :ov");
define("ACCOUNT_CONTRA_PARTIDA"," select T0.ACCOUNTID from BankAccountTable T0 where T0.DATAAREAID='".COMPANY."' and T0.CURRENCYCODE = 'MXN'");
define("DIARIO_NAME","SELECT DISTINCT JOURNALNAME AS 'cuenta' FROM dbo.LEDGERJOURNALTABLE WHERE JOURNALNAME LIKE 'CB_%' ORDER BY JOURNALNAME");
define("NUM_CLIENT_SALES","select count(T0.SALESID) as total from SALESTABLE T0 where t0.SALESSTATUS=3 and T0.CUSTACCOUNT=:cliente");
define("GET_PAYMODE_FROM_OV","select PAYMMODE from SALESTABLE where SALESID = :id");
define("COUNT_FACTURAS_USER","select count(tipo) as 'cant', USUARIO from ".INTERNA.".dbo.LogInax where TIPO ='factura' and fecha BETWEEN :fechaInicial AND :fechaActual group by USUARIO order by usuario;");
define("COUNT_FACTURAS_SUCURSAL","select count(tipo) as 'cant', IP from ".INTERNA.".dbo.LogInax where TIPO ='factura' and fecha BETWEEN :fechaInicial AND :fechaActual group by IP order by cant desc;");
define("DATA_SUCURSAL_LIST","select * from ".INTERNA.".dbo.sucursal;");
define("FACTURAS_INAX","select COUNT(INVOICEID) TOTAL, INVENTSITEID from CUSTINVOICEJOUR T0 WHERE SALESID!='' AND STF_USER !='' AND SALESTYPE=3 AND DATAAREAID='".COMPANY."' AND INVOICEDATE BETWEEN :fechaInicial AND :fechaActual GROUP BY INVENTSITEID ORDER BY INVENTSITEID");
DEFINE("FACTURAS_DYN","select COUNT(INVOICEID) TOTAL,INVENTSITEID from CUSTINVOICEJOUR WHERE SALESID!='' AND STF_USER ='' AND SALESTYPE=3 AND DATAAREAID='".COMPANY."' AND INVOICEDATE BETWEEN :fechaInicial AND :fechaActual GROUP BY INVENTSITEID ORDER BY INVENTSITEID");
define("CLIENTES_PASA_OV","SELECT T0.salesid,T0.custaccount,T0.salesname,T0.dlvmode,T0.inventsiteid
				,T0.inventlocationid
			,(SELECT TDIRP.NAME FROM   dirpartytable TDIRP INNER JOIN hcmworker HCMW ON ( TDIRP.recid = HCMW.person ) WHERE  HCMW.recid = T0.workersalestaker) AS 'VENDEDOR'
			,T0.CREATEDDATETIME
            ,t0.SALESSTATUS
            ,(select top 1 T4.PACKINGSLIPID from  ##tbl1 T4 where T4.SALESID=T0.SALESID)  AS PACKINGSLIPIDJOUR
FROM		SALESTABLE T0
			LEFT JOIN HCMWORKER T2 ON (T2.RECID = T0.WORKERSALESTAKER)
			LEFT JOIN DIRPARTYTABLE T3 ON (T3.RECID = T2.PERSON)
	WHERE		(T0.CREATEDDATETIME > DATEADD(MONTH, - 1, GETDATE())) and T0.SALESNAME like ? and t0.SALESSTATUS=2
	AND T0.DATAAREAID = '".COMPANY."' order by T0.CREATEDDATETIME desc;");
define("CLIENTES_PASA_OV_2", "SELECT T0.salesid,T0.custaccount,T0.salesname,T0.dlvmode,T0.inventsiteid
				,T0.inventlocationid
			,(SELECT TDIRP.NAME FROM   dirpartytable TDIRP INNER JOIN hcmworker HCMW ON ( TDIRP.recid = HCMW.person ) WHERE  HCMW.recid = T0.workersalestaker) AS 'VENDEDOR'
			,T0.CREATEDDATETIME
            ,t0.SALESSTATUS
            ,(select top 1 T4.PACKINGSLIPID from  ##tbl1 T4 where T4.SALESID=T0.SALESID)  AS PACKINGSLIPIDJOUR
FROM		SALESTABLE T0
			LEFT JOIN HCMWORKER T2 ON (T2.RECID = T0.WORKERSALESTAKER)
			LEFT JOIN DIRPARTYTABLE T3 ON (T3.RECID = T2.PERSON)
	WHERE		(T0.CREATEDDATETIME > DATEADD(MONTH, - 1, GETDATE())) and T0.salesid like ? and t0.SALESSTATUS=2
	AND T0.DATAAREAID = '".COMPANY."' order by T0.CREATEDDATETIME desc;");
define("TOTAL_OV","SELECT SUM(LINEAMOUNT) AS TOTAL FROM	SALESLINE WHERE	SALESID = :id AND DATAAREAID = '".COMPANY."' "); 
define("DIARIO_LIST","SELECT top 1000 JOURNALNUM,NAME,JOURNALNAME,POSTEDDATETIME FROM dbo.LEDGERJOURNALTABLE WHERE DATAAREAID='".COMPANY."' order by JOURNALNUM desc");
define("DIARIO_DETALLE","select T0.MODIFIEDDATETIME,T0.ACCOUNTTYPE,(select T1.DISPLAYVALUE FROM  DimensionAttributeValueCombination T1 where t1.RECID=T0.LedgerDimension) as CUSTOMER,T0.MARKEDINVOICE,T0.TXT,T0.AMOUNTCURCREDIT,OffsetAccountType,(select T1.DISPLAYVALUE FROM  DimensionAttributeValueCombination T1 where t1.RECID=T0.OffsetLedgerDimension) as CUENTACONTRA,T0.PAYMMODE,T0.LINENUM  from LedgerJournalTrans T0 where JOURNALNUM= :diario order by T0.AMOUNTCURCREDIT");
define("FACTURAS_SALDO","SELECT T1.INVOICE,
	SUM(T0.INVOICEAMOUNT - T1.SETTLEAMOUNTCUR) 'Saldo' 
        FROM CUSTINVOICEJOUR T0
        INNER JOIN CUSTTRANS T1 ON T1.VOUCHER=T0.LEDGERVOUCHER
        WHERE T1.INVOICE LIKE 'FV%' 
         AND T0.DATAAREAID = '".COMPANY."'
         AND T1.DATAAREAID = '".COMPANY."' 
         GROUP BY T1.INVOICE"); 
define("USUARIO_DIARIO","select diario from ".INTERNA.".dbo.diarioCuenta where usuario= :usuario");
define("CUENTAS_PAGO","select * from ".INTERNA.".dbo.diariosCreditoCuenta");

